### ISSUE TITLE
NuGet dependencies version spec has very obscure place

### ISSUE THREAD

**Issue by konste** [fsprojects/Paket#1016]
This document http://fsprojects.github.io/Paket/nuget-dependencies.html describes two different (?) ways of describing dependency version constraint - **Pinned version constraint** (nuget Example = 1.2.3) and **Use exactly this version constraint** (nuget Example == 1.2.3). Despite my best effort I cannot grasp what's the difference between those. Would be great to comment on that in that document.

Thank you!
Konstantin

**Comment by forki** [comment]
I admit the description is not good.

1) Usually you would use = if you need to pin a lib.
2) In some case you can get a version conflict in transistive dependencies, then == allows you to manually resolve the conflict. But this is unrelated to case 1 where you pin because of API incompabilities or somehting like that.
