### ISSUE TITLE
Paket bootstrapper always downloads prereleases even if paket.exe is latest

### ISSUE THREAD

**Issue by forki** [fsprojects/Paket#1041]
run paket.bootstrappper.exe prerelease 
==> downloads latest prerelease

run paket.bootstrappper.exe prerelease 
==> downloads latest prerelease again

**Comment by baronfel** [comment]
Looks to be because we're setting the FileInfoVersion to be whole versions, not prereleases, in the assembly info of the prerelease exe.  So when we go fetch versions, the version to be downloaded is never equal to the version locally.

We could either
a) compare based on the non-prerelease parts of versions for the 'is same version' check, or
b) set prerelease versions in the prerelease executables and allow the check to occur as normal

I prefer (b) because if we compare on normalized versions then we'll never download subsequent versions of a particular major/minor/patch version. For example,  2.0.0-beta005 and 2.0.0-beta006 would both compare down to 2.0.0 in scheme (a).

What do you want to do?

**Comment by baronfel** [comment]
probably need to look at FAKE's Release Notes helper, because that's how Paket sets the fileversion number.  If it only parses stable version numbers, then we'll need to think of another solution.

**Comment by baronfel** [comment]
however! we do set the [informational version](https://github.com/fsprojects/Paket/blob/master/build.fsx#L94) at build/release time, so if we switch to reading that, then we should have all the detail we need?
