### ISSUE TITLE
Error when adding existing project with Paket to the solution

### ISSUE THREAD

**Issue by Horusiath** [fsprojects/Paket#1131]
I've encountered an error message box in Visual Studio when trying to move project folder (having Paket already integrated) into a different directory and adding it again to the solution. Error message:

> The imported project "&lt;project_path&gt;\\..\.paket\paket.targets" was not found. Confirm that the path in the &lt;Import&gt; declaration is correct, and that the file exists on disk. &lt;csproj_path&gt;

My guess is that after adding an existing project with `<Import Project="relative path to paket.targets" />` already set on, Paket won't try to readjust the path to the current solution, target project has been imported to. So if the project folder was moved or copied, path to `paket.targets` becomes invalid and an error message will be thrown.

**Comment by forki** [comment]
Usually a run of "paket install" should fix that. Any chance for me to
reproduce?

**Comment by Horusiath** [comment]
The problem is that Visual Studio is rejecting adding existing project in the first place. I think that basic reproduce path could be made like that:

Given following directory structure:

    root
        \.paket folder
        \src
            \folderA
                \A.csproj (with Paket <Import> set)
            \*.sln file

, try to move `folderA` with csproj like the following:

    root
        \.paket folder
        \src
            \folderB
                \folderA
                    A.csproj
            \*.sln file

To mirror changes, you'd need to remove A.csproj from the solution and add it again as the existing project. Then the error should occur (I'm using VS2015). Since path to *paket.targets* is set in the csproj file and it's relative to it, it's pointing to the invalid directory.

**Comment by forki** [comment]
Just run paket install before you readd the project. Paket doesn't care if
the project is referenced in a sln. It should fix all paths and then you
can add it again.
On Oct 12, 2015 7:44 PM, "Bartosz Sypytkowski" <notifications@github.com>
wrote:

The problem is that Visual Studio is rejecting adding existing project in
the first place. I think that basic reproduce path could be made like that:

Given following directory structure:

root
    \.paket folder
    \src
        \folderA
            \A.csproj (with Paket <Import> set)
        \*.sln file

, try to move folderA with csproj like the following:

root
    \.paket folder
    \src
        \folderB
            \folderA
                A.csproj
        \*.sln file

To mirror changes, you'd need to remove A.csproj from the solution and add
it again as the existing project. Then the error should occur (I'm using
VS2015). Since path to *paket.targets* is set in the csproj file and it's
relative to it, it's pointing to the invalid directory.

—
Reply to this email directly or view it on GitHub
<https://github.com/fsprojects/Paket/issues/1131#issuecomment-147472702>.
