### ISSUE TITLE
Paket install does an update for pre-release only packages

### ISSUE THREAD

**Issue by vbfox** [fsprojects/Paket#1304]
It seem that while `install` doesn't update the version for non-prerelease packages or for pre-releases explicitly asked via `prerelease` it does it for packages that only have pre-release versions.

Pinning the pre-release package to a specific pre-release or even just specifying `prerelease` without version specification fixes the bug.

Given the `paket.dependencies` : 

```text
source https://nuget.org/api/v2
nuget StyleCop.Analyzers
```
and the `paket.lock` :
```text
NUGET
  remote: https://nuget.org/api/v2
  specs:
    StyleCop.Analyzers (1.0.0-rc1)
```

running install does an unwanted update :
```text
c:\Code\paket_repro_install_update>paket install
Paket version 2.35.0.0
Resolving packages for group Main:
 - StyleCop.Analyzers 1.0.0-rc2
Locked version resolution written to c:\Code\paket_repro_install_update\paket.lock
3 seconds - ready.
```

Producing the following lock file :

```text
NUGET
  remote: https://nuget.org/api/v2
  specs:
    StyleCop.Analyzers (1.0.0-rc2)
```

**Comment by forki** [comment]
This is by design. 
In your dependencies file you specify that you want to have latest release. During last update process could only find prereleases. That violates the dependency definition, but is accepted to make things a bit easier.
Due to the violation of the dependencies file, paket will always try to update that package and when the first release comes out it will be able to solve that violation. 
As you already figured out "prerelease" restriction in the dependencies file works and keeps lock file stable.

**Comment by vbfox** [comment]
Ok the bug is then that the previous install/update that took a pre-release version as a fallback didn't warn about it.

**Comment by forki** [comment]
I think we added this recently.

**Comment by vbfox** [comment]
I'll check that, maybe it's due to us pining paket version and always lagging a few versions so we never got the new warning.
