### ISSUE TITLE
[Enhancement?] Command to have paket create a .fsx with references for a particular dependency group (or all dependencies)

### ISSUE THREAD

**Issue by baronfel** [fsprojects/Paket#1362]
I'm thinking of, in FAKE scripts especially, it would be useful to generate the includes for the 'dev-dependencies' or 'build' group as a single .fsx that could be loaded.  As it is I have to go load a bunch of disparate dependencies that are manual when I work on a script.

Problems: which framework version should the scripts be?  should we generate a multitude of scripts, one for each framework, with the references automatically sorted out based on the target framework?

**Comment by isaacabraham** [comment]
Had the same idea this week. VFPT already does this but it relies on VS-specific tooling and already has the references.

IMHO, this feature should behave with the same items added as #r as those that are added as references to .vbproj, .csproj and .fsproj files.

I haven't dug into the Paket source in a while now, but I can think of at least two or three places that perform at least part of what this would need: -

1. Code that injects references into project files.
2. Code that generates binding redirects.

Both of these need to get a list of assemblies. I don't recall if they both use the same code or if they are different. This could be an opportunity to refactor the code for a more generalised "give me all assemblies for this group and lock file" or similar?

We would still need to consider: -

1. Reference order. Might need to actually look at the assembly metadata in order to figure this out.
2. #load of fsx files?
3. What about non-NuGet dependencies e.g. github?

**Comment by matthid** [comment]
paket can create load scripts now
