### ISSUE TITLE
Allow specifying extra sources from outside paket.dependencies

### ISSUE THREAD

**Issue by Tarmil** [fsprojects/Paket#1386]
Probably as a command line argument, or maybe an environment variable.

Here is my use case: we have an internal CI server with a bunch of projects which, upon successful build, copy the resulting nupkg to a directory where dependent projects can find them. With our current NuGet setup, this directory is specified in the user nuget.config and it works well. If we switch to Paket, we'd need to add this directory to paket.dependencies; but since these are OSS projects, we don't want to expose our file system paths. Plus `paket update` would fail when building on another machine that doesn't have that path.

I'll give a shot at a PR if you guys agree with the idea.

**Comment by forki** [comment]
currently I don't think I want to have source that are not specified in the dependencies file. It has many advantages that you can easily see what's happening from one global view.

I don't really get why OSS projects would depend on nupgks in a local folder. If I colne that project then why would I need to put nukgs in a special folder? Why aren't these packages available on nuget or myget? Could you please elaborate on that?

**Comment by Tarmil** [comment]
We have a main repository, WebSharper, and dozens of smaller repositories for libraries and extensions that depend on it. We don't want to publish WebSharper.nupkg before CI has ensured that it doesn't break any of these libraries.

**Comment by forki** [comment]
Most users use myget or a local nuget feed for this.

But maybe you can take a look at
http://fsprojects.github.io/Paket/git-dependencies.html we plan to make
that workflow available.

We probably also introduce an additional overwrite file (like cargo does)
similar to what you propose here (that can be gitignored ). But that will
go into v3

**Comment by forki** [comment]
One of open questions is what happens with the lock file.

**Comment by forki** [comment]
From the cargo docs: http://doc.crates.io/guide.html#overriding-dependencies 

Maybe we can come up with something similar for a `paket.dependencies.overwrite` file or something like that.

**Comment by Tarmil** [comment]
We do have an internal nuget feed that grabs straight from the directory I mentioned, and I guess I could use that indeed. But I'd still prefer not to commit internal URLs if I can avoid it. And not to have to edit every single project if that URL ever changes :)

Maybe a less invasive solution would be to allow environment variable expansion in a source's path, just like it already works for the username and password. And if a source line, after variable expansion, results in an empty path, it would be ignored.

**Comment by forki** [comment]
Yes that would probably work for you. ;-)

But it's not really the way I want to go. I think the cargo way is much
better.

**Comment by pms1969** [comment]
I have another use case where this would be particularly handy.

We have have some 130'ish solutions that make up our project landscape.  All are pretty much actively developed.  For regular development, we always want to be on the latest available package, so the paket.dependencies has no version numbers in it.  At some point, an uber build goes green, and we have a release candidate.  At this point, everything is tagged, so that we can branch from it if it becomes an actual release, and we need to patch it.

Workflow then becomes a little more complicated.  We'd obviously restore from our main repo's, but would then like to update from our patch repo.  Now many of the packages will not be available in the patch repo, because they haven't been patched, but the ones that are, we would like to only pick up the latest out of our patch repo, because the main repo may have moved several versions past what is going to be made available in the patch.  Lock files aren't committed, but are kept in a safe place for each release candidate, so are retrievable during patch builds.

In this situation, it would be handy to have some way to override the sources, so that the update only uses the patch repo.  I've got a workaround, which involves backing up the paket.dependencies, and rewriting it for the update during a patch build, but that just seems ugly.

**Comment by michael-baker** [comment]
We have a similar workflow to @pms1969. We would love to be able to specify our internal NuGet server URL globally for when working on a specific configuration of our product. As we have several internal NuGet servers and updating the URL across 500+ files when branching/merging is rather tedious.

**Comment by smoothdeveloper** [comment]
Cabal is kind of the golden rule to some extent, please check add-source on this page: https://www.haskell.org/cabal/users-guide/installing-packages.html

Ideally paket should allow to override whatever is in paket.dependencies with a set of invocations storing the overrides in a working folder.

**Comment by kevinbosman** [comment]
We have a different use case where we have limited and slow internet bandwidth. We have 100's of solutions and want our in-house devs and our build server to use our private NuGet mirror server, but remote devs should never know about our private server, or indeed may want to use their own private servers instead. Editing or maintaining multiple copies of paket.dependencies is extremely tedious.

**Comment by forki** [comment]
I'd like to see a proposal syntax for a new file that allows to override sources.

**Comment by tsibelman** [comment]
I think it need to be exactly like paket.dependencies and should just override them

**Comment by forki** [comment]
Ok but since we have multiple sources need a matching procedure.

**Comment by Stift** [comment]
two different servers means also two different sources for me. It's very easy with these described use cases to screw up all debugging and repeatable builds. 
I fear that this may be a way which is hard to consitently describe as the lock file should always describe the way the ci sees the world and devs need to prove that. Else you come close to a nightmare.

**Comment by Stift** [comment]
@Tarmil why don't you go Myget and use this as development nuget source? Which is absolutely fine and they especially offer this to OSS for free! https://www.myget.org/opensource
Then you push your stuff to myget on a private feed and fine. But in the end as OSS you need to find an easy way to attract others developers as well. The more you put burden on them (configuration before starting) the less ppl will join.

**Comment by tsibelman** [comment]
@forki  maybe source orig => replacement

**Comment by Stift** [comment]
Here is what we have.
We have a nuget server with some feeds for devs. If a dev wants to test a package he can put it in some directory like `ext\nuget` (excluded in .gitignore) where he can put some dev stuff in and check this. Upon committing anything to the central repo he has to clean it up, so that CI won't fail.
The idea of different packages and a source is in our case that each package is an individual product which is tested and proved in one location (its origin).

**Comment by matthid** [comment]
`paket.local`?
