### ISSUE TITLE
Create new strategy modifier that allows to use lowest matching

### ISSUE THREAD

**Issue by inosik** [fsprojects/Paket#1409]
With the following `paket.dependencies`, I would expect the earliest of v3.x.x for Main and B, but Paket resolves the package to version 4.0.0.1 in every group:
```
source https://nuget.org/api/v2

nuget FSharp.Core !>= 3

group B
source https://nuget.org/api/v2
strategy: min

nuget FSharp.Core >= 3

group C
source https://nuget.org/api/v2

nuget FSharp.Core @>= 3

group D
source https://nuget.org/api/v2
strategy: max

nuget FSharp.Core >= 3
```

**Comment by forki** [comment]
Strategy modifier only works on transitive dependencies - never on the dependency itself. 

That said I know some people (cc @eiriktsarpalis) would like to see an option to use a new  minimum version operator on the direct dependency. 

/cc @mrinaldi

**Comment by inosik** [comment]
Did it always work like this? I could swear I've seen this working as described above before.

**Comment by forki** [comment]
Yes. As far as I remember it always worked like that. At least it was always meant to work like that since it is a compatibility mode to nuget.

**Comment by mrinaldi** [comment]
Indeed. In fact, on the docs it clearly states only transitive dependencies are affected.

If we want this behavior, we should introduce a new modifier, in my opinion.

**Comment by inosik** [comment]
Closing this one, since I didn't read the docs carefully enough.

**Comment by forki** [comment]
How about:

   nuget FSharp.Core >= 3 lowest-matching

**Comment by forki** [comment]
this is also needed for https://github.com/fsprojects/FSharp.Data.TypeProviders/blob/master/paket.dependencies#L7

**Comment by dsyme** [comment]
Perhaps this is better:

    nuget FSharp.Core >= 3 min

I somehow thought "strategy: min" would do this, though [the docs](http://fsprojects.github.io/Paket/dependencies-file.html) do make it clear that it doesn't:

> Note, however, that all direct dependencies still get their lastest matching versions, no matter the value of the strategy option.

**Comment by eiriktsarpalis** [comment]
IMHO the fact that we are using separate syntax for transitive-only and inclusive strategy modifiers seems a bit confusing. My proposal would be to retain the same syntax (i.e. ! and @) and specify whether it should be restricted to transitive dependencies via a trailing keyword. For instance:
```
nuget FSharp.Core @>= 3 [inclusive|transitive-only]
```
Adding no keyword would translate to transitive-only, in the interest of preserving backwards compatibility.

That said, I like @dsyme's proposal of adopting the min/max keyword, but I would prefer it if this replaced the existing strategy modifiers as well.

**Comment by forki** [comment]
I think we are talking about two different things here. There existing strategy modifier syntax looks related, but is used for something different. 

As @dsyme often points out there is a difference for apps and libs. 

Let's start with the case where I want to build an app:
Usually I want to use the latest (compatible) version of my dependencies in order to get all the nice bug fixes. But sometimes version constraints of transitive dependencies are too open and taking latest transitive dependencies breaks my app. Therefore we have the min strategy that makes paket resolve in NuGet compatible fashion. That way I still get latest direct dependencies, but transitives are resolved conservatively. 

If I develope a lib things change a bit:
In general I try to make my lib to work with the biggest possible range of dependencies. For this I should test my lib in combination with many of its dependencies. Unfortunate that is a bit unpractical and people settle to test against lowest possible dependency (and hope newer dependencies won't break). In order to do that we need to instruct paket to take the lowest (matching) version of a direct dependency. The resolution strategy of transitive dependencies is unrelated to that idea. I still might to use "NuGet compatibility mode", but not always. 

With this in mind I don't think mixing both idea is the way to go. Unfortunately I also don't like my proposal - so I hope to see a better idea.

**Comment by forki** [comment]
There is another case for lib development: I often want to test my lib against the latest version of its dependencies in order to get notified when someone pushes a breaking dependency. 
This is already easy to achieve: I can set up an additional  daily build that just runs "paket update" before the build.

**Comment by forki** [comment]
I now have a working implementation - only the syntax is open..

**Comment by forki** [comment]
I propose the following syntax:

    source http://www.nuget.org/api/v2
    nuget Microsoft.AspNet.Mvc >= 6.0.0 lowest-matching: true

and for group-wide settings:

    source http://www.nuget.org/api/v2
    lowest-matching: true
    nuget Microsoft.AspNet.Mvc >= 6.0.0

**Comment by forki** [comment]
After talking with @agross we came up with something that is more similar to ! and @:

    source http://www.nuget.org/api/v2
    nuget Microsoft.AspNet.Mvc {>= 6.0.0
 
for group-wide settings I still think the following is good:

    source http://www.nuget.org/api/v2
    lowest-matching: true
    nuget Microsoft.AspNet.Mvc >= 6.0.0

we would also support the symmetric:

    source http://www.nuget.org/api/v2
    lowest-matching: true
    nuget Microsoft.AspNet.Mvc }>= 6.0.0

this would also go:

    source http://www.nuget.org/api/v2
    nuget Microsoft.AspNet.Mvc {!>= 6.0.0

that's a lot of operator magic, but I think the main use case is:

    source http://www.nuget.org/api/v2
    lowest-matching: true
    nuget Microsoft.AspNet.Mvc >= 6.0.0

so that would be fine.

**Comment by inosik** [comment]
What about `match: [lowest|highest]`? But `match-lowest: true` would be fine, too. `{` and `}` look pretty cryptic, though.

**Comment by cloudRoutine** [comment]
I'm also a fan of `match-lowest` & `match-highest`

**Comment by forki** [comment]
Ok so people are voting against operator hell.

So we're back to the following syntax:

    source http://www.nuget.org/api/v2
    nuget Microsoft.AspNet.Mvc >= 6.0.0 lowest-matching: true

and for group-wide settings:

    source http://www.nuget.org/api/v2
    lowest-matching: true
    nuget Microsoft.AspNet.Mvc >= 6.0.0

In this case I think we should also add alternative syntax for `!`:

    source http://www.nuget.org/api/v2
    nuget Microsoft.AspNet.Mvc >= 6.0.0 strategy: min

and for `@`:

    source http://www.nuget.org/api/v2
    nuget Microsoft.AspNet.Mvc >= 6.0.0 strategy: max

**Comment by cloudRoutine** [comment]
:+1:

**Comment by inosik** [comment]
Maybe `highest-matching: false` would be better, as it would (kind of) indicate that this is the default for Paket. Just like `import_targets` and `copy_local`.

**Comment by forki** [comment]
this fixes https://github.com/fsprojects/FSharp.Data.TypeProviders/pull/7
