### ISSUE TITLE
Run paket install from another folder than project-root-folder

### ISSUE THREAD

**Issue by andmos** [fsprojects/Paket#1438]
Hi! 
I notice that if I have my build script in the folder lever outside my source code folder like this: 

├── Repo
│   └── src
│       └── .paket
├── build.bat
└── tools
│   └── build.csx
│   └── common.csx

Calling ``build.bat`` from the Repo folder  (``src/.paket/paket.exe install``) results in ``Paket failed with:
	Could not find 'paket.dependencies'. To use Paket with this solution, please run 'paket init' first.``
The ``paket.dependencies`` file is located in ``Repo/src/paket.dependencies``. 
A small thing I know, but should it be possible to pass the location of the dependencies file to the install command?

**Comment by forki** [comment]
This is a frequently asked question, I think we should add it to the faq.

Very old paket versions allowed to specify the paket.dependencies location.
We disabled that because we have very strong opinions about that. We
believe the dependencies are so important that they belong in the root of
the repository. People should know about the dependencies.

That said: if you don't agree with that (but please take some time and
think about it) you can use the build.bat to change the working folder.

**Comment by andmos** [comment]
Thanks for reply! What I am doing today is exactly setting the moving path.

**Comment by forki** [comment]
As I said: changing working dir will work, but it's not recommended.

**Comment by andmos** [comment]
I see your point. I think we should move out the packages folder to the root lever.
