### ISSUE TITLE
Paket has trouble resolving .NET Core dependency lists

### ISSUE THREAD

**Issue by dsyme** [fsprojects/Paket#1610]
### Description

I've been trying to use Paket to resolve the kind of dependency listings we're seeing in project.json files for compiling F# .NET Core components.  I'm finding that Paket rarely succeeds in resolving these dependency lists.

### Repro steps

Create a ``paket.dependencies`` for [this dependency listing](https://gist.github.com/dsyme/c6dd96f905cda7a3edd0590aaff459cf), taken straight from [this project.json](https://github.com/Microsoft/visualfsharp/pull/1062/files#diff-f17ec802398873e609894277562fb87aR1)

Expected: the dependency list resolves OK in reasonable time

Actual: I aborted the operation after about 8 minutes, with [this log](https://gist.github.com/dsyme/a29ff9d2701b9dd451baa7997b4e46d7)

**Comment by tsibelman** [comment]
I think you define framework in your pake.dependency it will work faster

**Comment by forki** [comment]
Thanks for reporting.

If the resolver needs that longer it usually means there is no valid
resolution. Paket is much more restrictive about that. But I assume there
still new things to discover here...
On Apr 14, 2016 11:04, "Don Syme" <notifications@github.com> wrote:

Description

I've been trying to use Paket to resolve the kind of dependency listings
we're seeing in project.json files for compiling F# .NET Core components.
I'm finding that Paket rarely succeeds in resolving these dependency lists.
Repro steps

Create a paket.dependencies for this dependency listing, taken straight
from this project.json
<https://github.com/Microsoft/visualfsharp/pull/1062/files#diff-f17ec802398873e609894277562fb87aR1>

source https://www.myget.org/F/dotnet-core/api/v3/index.json
source https://api.nuget.org/v3/index.json
source https://www.nuget.org/api/v2/


nuget Microsoft.NETCore.Platforms 1.0.1-rc2-23911
nuget NETStandard.Library 1.5.0-rc2-23911
nuget System.Collections.Immutable 1.2.0-rc2-23911
nuget System.Diagnostics.Process 4.1.0-rc2-23911
nuget System.Diagnostics.TraceSource 4.0.0-rc2-23911
nuget System.Linq.Expressions 4.0.11-rc2-23911
nuget System.Linq.Queryable 4.0.1-rc2-23911
nuget System.Net.Requests 4.0.11-rc2-23911
nuget System.Reflection.Emit 4.0.1-rc2-23911
nuget System.Reflection.Emit.ILGeneration 4.0.1-rc2-23911
nuget System.Reflection.Metadata 1.3.0-rc2-23911
nuget System.Reflection.TypeExtensions 4.1.0-rc2-23911
nuget System.Runtime.InteropServices 4.1.0-rc2-23911
nuget System.Runtime.InteropServices.PInvoke 4.0.0-rc2-23911
nuget System.Runtime.Loader 4.0.0-rc2-23911
nuget System.Security.Cryptography.Algorithms 4.1.0-rc2-23911
nuget System.Security.Cryptography.Primitives 4.0.0-rc2-23911
nuget System.Threading.Tasks.Parallel 4.0.1-rc2-23911
nuget System.Threading.Thread 4.0.0-rc2-23911
nuget System.Threading.ThreadPool 4.0.10-rc2-23911
nuget Microsoft.DiaSymReader.PortablePdb 1.0.0-rc-60301
nuget Microsoft.DiaSymReader 1.0.7

Expected: the dependency list resolves OK in reasonable time

Actual: I aborted the operation after about 8 minutes:

C:\misc\repro-54>.paket\paket.exe update
Paket version 2.60.2.0
Resolving packages for group Main:
 - System.Diagnostics.Process is pinned to 4.1.0-rc2-23911
 - System.Reflection.TypeExtensions is pinned to 4.1.0-rc2-23911
 - System.Runtime.InteropServices is pinned to 4.1.0-rc2-23911
 - System.Security.Cryptography.Algorithms is pinned to 4.1.0-rc2-23911
 - System.Linq.Expressions is pinned to 4.0.11-rc2-23911
 - System.Net.Requests is pinned to 4.0.11-rc2-23911
 - System.Threading.ThreadPool is pinned to 4.0.10-rc2-23911
 - System.Linq.Queryable is pinned to 4.0.1-rc2-23911
 - System.Reflection.Emit is pinned to 4.0.1-rc2-23911
 - System.Reflection.Emit.ILGeneration is pinned to 4.0.1-rc2-23911
 - System.Threading.Tasks.Parallel is pinned to 4.0.1-rc2-23911
 - System.Diagnostics.TraceSource is pinned to 4.0.0-rc2-23911
 - System.Runtime.InteropServices.PInvoke is pinned to 4.0.0-rc2-23911
 - System.Runtime.Loader is pinned to 4.0.0-rc2-23911
 - System.Security.Cryptography.Primitives is pinned to 4.0.0-rc2-23911
 - System.Threading.Thread is pinned to 4.0.0-rc2-23911
 - NETStandard.Library is pinned to 1.5.0-rc2-23911
 - System.Reflection.Metadata is pinned to 1.3.0-rc2-23911
 - System.Collections.Immutable is pinned to 1.2.0-rc2-23911
 - Microsoft.DiaSymReader is pinned to 1.0.7
 - Microsoft.NETCore.Platforms is pinned to 1.0.1-rc2-23911
 - Microsoft.DiaSymReader.PortablePdb is pinned to 1.0.0-rc-60301
 - System.AppContext 4.1.0-rc3-24014-01
 - System.Diagnostics.Tracing 4.1.0-rc3-24014-01
 - System.IO 4.1.0-rc3-24014-01
 - System.IO.Compression 4.1.0-rc3-24014-01
 - System.Linq 4.1.0-rc3-24014-01
 - System.Net.Sockets 4.1.0-rc3-24014-01
 - System.Reflection 4.1.0-rc3-24014-01
 - System.Runtime 4.1.0-rc3-24014-01
 - System.Runtime.Extensions 4.1.0-rc3-24014-01
 - System.Collections.Concurrent 4.0.12-rc3-24014-01
 - System.ObjectModel 4.0.12-rc3-24014-01
 - System.Text.RegularExpressions 4.0.12-rc3-24014-01
 - System.Collections 4.0.11-rc3-24014-01
 - System.Diagnostics.Debug 4.0.11-rc3-24014-01
 - System.Globalization 4.0.11-rc3-24014-01
 - System.Net.Primitives 4.0.11-rc3-24014-01
 - System.Text.Encoding 4.0.11-rc3-24014-01
 - System.Text.Encoding.Extensions 4.0.11-rc3-24014-01
 - System.Threading 4.0.11-rc3-24014-01
 - System.Threading.Tasks 4.0.11-rc3-24014-01
 - System.Xml.ReaderWriter 4.0.11-rc3-24014-01
 - System.Xml.XDocument 4.0.11-rc3-24014-01
 - Microsoft.Win32.Primitives 4.0.1-rc3-24014-01
 - System.Diagnostics.Tools 4.0.1-rc3-24014-01
 - System.Globalization.Calendars 4.0.1-rc3-24014-01
 - System.IO.Compression.ZipFile 4.0.1-rc3-24014-01
 - System.IO.FileSystem 4.0.1-rc3-24014-01
 - System.IO.FileSystem.Primitives 4.0.1-rc3-24014-01
 - System.Net.Http 4.1.0-rc3-24014-01
 - System.Reflection.Extensions 4.0.1-rc3-24014-01
 - System.Reflection.Primitives 4.0.1-rc3-24014-01
 - System.Resources.ResourceManager 4.0.1-rc3-24014-01
 - System.Runtime.Handles 4.0.1-rc3-24014-01
 - System.Runtime.Numerics 4.0.1-rc3-24014-01
 - System.Threading.Timer 4.0.1-rc3-24014-01
 - System.Net.WebHeaderCollection 4.0.1-rc3-24014-01
 - System.Console 4.0.0-rc3-24014-01
 - System.Runtime.InteropServices.RuntimeInformation 4.0.0-rc3-24014-01
 - Microsoft.NETCore.Runtime 1.0.2-rc3-24014-01
 - Microsoft.NETCore.Targets 1.0.1-rc3-24014-01
 - Microsoft.DotNet.CoreHost 0.0.1-beta-00001
 - Microsoft.NETCore.Targets 1.0.1-rc3-24013-00
 - System.Net.Http 4.0.1-rc3-24013-00
  Could not resolve package System.Runtime.InteropServices:
   - Dependencies file requested package System.Runtime.InteropServices: 4.1.0-r
c2-23911 (no prereleases)
   - System.IO.Compression 4.1.0-rc3-24014-01 requested package System.Runtime.I
nteropServices: >= 4.1.0-rc3-24014-01
   - System.Net.Http 4.0.1-rc3-24013-00 requested package System.Runtime.Interop
Services: >= 4.1.0-rc3-24013-00
   - System.Reflection.Metadata 1.3.0-rc2-23911 requested package System.Runtime
.InteropServices: >= 4.0.21-rc2-23911
   - System.Xml.ReaderWriter 4.0.11-rc3-24014-01 requested package System.Runtim
e.InteropServices: >= 4.1.0-rc3-24014-01

The process is taking longer than expected.
Paket may still find a valid resolution, but this might take a while.
 - System.Net.Http 4.0.1-rc3-24012-00
 - System.Net.Http 4.0.1-rc3-24011-00
 - System.Net.Http 4.0.1-rc3-24008-00
 - System.Net.Http 4.0.1-rc3-24007-00
 - System.Net.Http 4.0.1-rc3-24006-00
 - System.Net.Http 4.0.1-rc3-24005-00
 - System.Net.Http 4.0.1-rc3-24004-00
 - System.Net.Http 4.0.1-rc3-24001-00
 - System.Net.Http 4.0.1-rc3-23931-00
 - System.Net.Http 4.0.1-rc3-23930-00
 - System.Net.Http 4.0.1-rc3-23929-00
 - System.Net.Http 4.0.1-rc3-23928-00
 - System.Net.Http 4.0.1-rc3-23925-00
 - System.Net.Http 4.0.1-rc3-23924
 - System.Net.Http 4.0.1-rc3-23923
 - System.Net.Http 4.0.1-rc3-23922
 - System.Net.Http 4.0.1-rc3-23921
 - System.Net.Http 4.0.1-rc3-23918
 - System.Net.Http 4.0.1-rc3-23916
 - System.Net.Http 4.0.1-rc3-23915
 - System.Net.Http 4.0.1-rc3-23914
 - System.Net.Http 4.0.1-rc3-23911
 - System.Net.Http 4.0.1-rc3-23910
 - System.Xml.ReaderWriter 4.0.11-rc3-24013-00
  Could not resolve package System.Runtime.InteropServices:
   - Dependencies file requested package System.Runtime.InteropServices: 4.1.0-r
c2-23911 (no prereleases)
   - System.IO.Compression 4.1.0-rc3-24014-01 requested package System.Runtime.I
nteropServices: >= 4.1.0-rc3-24014-01
   - System.Reflection.Metadata 1.3.0-rc2-23911 requested package System.Runtime
.InteropServices: >= 4.0.21-rc2-23911
   - System.Xml.ReaderWriter 4.0.11-rc3-24013-00 requested package System.Runtim
e.InteropServices: >= 4.1.0-rc3-24013-00

The process is taking longer than expected.
Paket may still find a valid resolution, but this might take a while.
 - System.Xml.ReaderWriter 4.0.11-rc3-24012-00
 - System.Xml.ReaderWriter 4.0.11-rc3-24011-00
  Could not resolve package System.Runtime.InteropServices:
   - Dependencies file requested package System.Runtime.InteropServices: 4.1.0-r
c2-23911 (no prereleases)
   - System.IO.Compression 4.1.0-rc3-24014-01 requested package System.Runtime.I
nteropServices: >= 4.1.0-rc3-24014-01
   - System.Net.Http 4.0.1-rc3-24011-00 requested package System.Runtime.Interop
Services: >= 4.1.0-rc3-24011-00
   - System.Reflection.Metadata 1.3.0-rc2-23911 requested package System.Runtime
.InteropServices: >= 4.0.21-rc2-23911
   - System.Xml.ReaderWriter 4.0.11-rc3-24011-00 requested package System.Runtim
e.InteropServices: >= 4.1.0-rc3-24011-00

The process is taking longer than expected.
Paket may still find a valid resolution, but this might take a while.
 - System.Xml.ReaderWriter 4.0.11-rc3-24008-00
  Could not resolve package System.Runtime.InteropServices:
   - Dependencies file requested package System.Runtime.InteropServices: 4.1.0-r
c2-23911 (no prereleases)
   - System.IO.Compression 4.1.0-rc3-24014-01 requested package System.Runtime.I
nteropServices: >= 4.1.0-rc3-24014-01
   - System.Net.Http 4.1.0-rc3-24014-01 requested package System.Runtime.Interop
Services: >= 4.1.0-rc3-24014-01
   - System.Reflection.Metadata 1.3.0-rc2-23911 requested package System.Runtime
.InteropServices: >= 4.0.21-rc2-23911
   - System.Xml.ReaderWriter 4.0.11-rc3-24008-00 requested package System.Runtim
e.InteropServices: >= 4.1.0-rc3-24008-00

The process is taking longer than expected.
Paket may still find a valid resolution, but this might take a while.
  Could not resolve package System.Runtime.InteropServices:
   - Dependencies file requested package System.Runtime.InteropServices: 4.1.0-r
c2-23911 (no prereleases)
   - System.IO.Compression 4.1.0-rc3-24014-01 requested package System.Runtime.I
nteropServices: >= 4.1.0-rc3-24014-01
   - System.Net.Http 4.0.1-rc3-23921 requested package System.Runtime.InteropSer
vices: >= 4.1.0-rc3-23921
   - System.Reflection.Metadata 1.3.0-rc2-23911 requested package System.Runtime
.InteropServices: >= 4.0.21-rc2-23911
   - System.Xml.ReaderWriter 4.0.11-rc3-24008-00 requested package System.Runtim
e.InteropServices: >= 4.1.0-rc3-24008-00

The process is taking longer than expected.
Paket may still find a valid resolution, but this might take a while.
 - System.Xml.ReaderWriter 4.0.11-rc3-24007-00
  Could not resolve package System.Runtime.InteropServices:
   - Dependencies file requested package System.Runtime.InteropServices: 4.1.0-r
c2-23911 (no prereleases)
   - System.IO.Compression 4.1.0-rc3-24014-01 requested package System.Runtime.I
nteropServices: >= 4.1.0-rc3-24014-01
   - System.Net.Http 4.0.1-rc3-23931-00 requested package System.Runtime.Interop
Services: >= 4.1.0-rc3-23931-00
   - System.Reflection.Metadata 1.3.0-rc2-23911 requested package System.Runtime
.InteropServices: >= 4.0.21-rc2-23911
   - System.Xml.ReaderWriter 4.0.11-rc3-24007-00 requested package System.Runtim
e.InteropServices: >= 4.1.0-rc3-24007-00

The process is taking longer than expected.
Paket may still find a valid resolution, but this might take a while.
 - System.Xml.ReaderWriter 4.0.11-rc3-24006-00
  Could not resolve package System.Runtime.InteropServices:
   - Dependencies file requested package System.Runtime.InteropServices: 4.1.0-r
c2-23911 (no prereleases)
   - System.IO.Compression 4.1.0-rc3-24014-01 requested package System.Runtime.I
nteropServices: >= 4.1.0-rc3-24014-01
   - System.Net.Http 4.0.1-rc3-24013-00 requested package System.Runtime.Interop
Services: >= 4.1.0-rc3-24013-00
   - System.Reflection.Metadata 1.3.0-rc2-23911 requested package System.Runtime
.InteropServices: >= 4.0.21-rc2-23911
   - System.Xml.ReaderWriter 4.0.11-rc3-24006-00 requested package System.Runtim
e.InteropServices: >= 4.1.0-rc3-24006-00

The process is taking longer than expected.
Paket may still find a valid resolution, but this might take a while.
  Could not resolve package System.Runtime.InteropServices:
   - Dependencies file requested package System.Runtime.InteropServices: 4.1.0-r
c2-23911 (no prereleases)
   - System.IO.Compression 4.1.0-rc3-24014-01 requested package System.Runtime.I
nteropServices: >= 4.1.0-rc3-24014-01
   - System.Net.Http 4.0.1-rc3-23921 requested package System.Runtime.InteropSer
vices: >= 4.1.0-rc3-23921
   - System.Reflection.Metadata 1.3.0-rc2-23911 requested package System.Runtime
.InteropServices: >= 4.0.21-rc2-23911
   - System.Xml.ReaderWriter 4.0.11-rc3-24006-00 requested package System.Runtim
e.InteropServices: >= 4.1.0-rc3-24006-00

The process is taking longer than expected.
Paket may still find a valid resolution, but this might take a while.
 - System.Xml.ReaderWriter 4.0.11-rc3-24005-00
  Could not resolve package System.Runtime.InteropServices:
   - Dependencies file requested package System.Runtime.InteropServices: 4.1.0-r
c2-23911 (no prereleases)
   - System.IO.Compression 4.1.0-rc3-24014-01 requested package System.Runtime.I
nteropServices: >= 4.1.0-rc3-24014-01
   - System.Net.Http 4.0.1-rc3-24004-00 requested package System.Runtime.Interop
Services: >= 4.1.0-rc3-24004-00
   - System.Reflection.Metadata 1.3.0-rc2-23911 requested package System.Runtime
.InteropServices: >= 4.0.21-rc2-23911
   - System.Xml.ReaderWriter 4.0.11-rc3-24005-00 requested package System.Runtim
e.InteropServices: >= 4.1.0-rc3-24005-00

The process is taking longer than expected.
Paket may still find a valid resolution, but this might take a while.
  Could not resolve package System.Runtime.InteropServices:
   - Dependencies file requested package System.Runtime.InteropServices: 4.1.0-r
c2-23911 (no prereleases)
   - System.IO.Compression 4.1.0-rc3-24014-01 requested package System.Runtime.I
nteropServices: >= 4.1.0-rc3-24014-01
   - System.Net.Http 4.0.1-rc3-23911 requested package System.Runtime.InteropSer
vices: >= 4.0.21-rc3-23911
   - System.Reflection.Metadata 1.3.0-rc2-23911 requested package System.Runtime
.InteropServices: >= 4.0.21-rc2-23911
   - System.Xml.ReaderWriter 4.0.11-rc3-24005-00 requested package System.Runtim
e.InteropServices: >= 4.1.0-rc3-24005-00

The process is taking longer than expected.
Paket may still find a valid resolution, but this might take a while.
 - System.Xml.ReaderWriter 4.0.11-rc3-24004-00
  Could not resolve package System.Runtime.InteropServices:
   - Dependencies file requested package System.Runtime.InteropServices: 4.1.0-r
c2-23911 (no prereleases)
   - System.IO.Compression 4.1.0-rc3-24014-01 requested package System.Runtime.I
nteropServices: >= 4.1.0-rc3-24014-01
   - System.Net.Http 4.0.1-rc3-24004-00 requested package System.Runtime.Interop
Services: >= 4.1.0-rc3-24004-00
   - System.Reflection.Metadata 1.3.0-rc2-23911 requested package System.Runtime
.InteropServices: >= 4.0.21-rc2-23911
   - System.Xml.ReaderWriter 4.0.11-rc3-24004-00 requested package System.Runtim
e.InteropServices: >= 4.1.0-rc3-24004-00

The process is taking longer than expected.
Paket may still find a valid resolution, but this might take a while.
  Could not resolve package System.Runtime.InteropServices:
   - Dependencies file requested package System.Runtime.InteropServices: 4.1.0-r
c2-23911 (no prereleases)
   - System.IO.Compression 4.1.0-rc3-24014-01 requested package System.Runtime.I
nteropServices: >= 4.1.0-rc3-24014-01
   - System.Net.Http 4.0.1-rc3-23922 requested package System.Runtime.InteropSer
vices: >= 4.1.0-rc3-23922
   - System.Reflection.Metadata 1.3.0-rc2-23911 requested package System.Runtime
.InteropServices: >= 4.0.21-rc2-23911
   - System.Xml.ReaderWriter 4.0.11-rc3-24004-00 requested package System.Runtim
e.InteropServices: >= 4.1.0-rc3-24004-00

The process is taking longer than expected.
Paket may still find a valid resolution, but this might take a while.
 - System.Xml.ReaderWriter 4.0.11-rc3-24001-00
  Could not resolve package System.Runtime.InteropServices:
   - Dependencies file requested package System.Runtime.InteropServices: 4.1.0-r
c2-23911 (no prereleases)
   - System.IO.Compression 4.1.0-rc3-24014-01 requested package System.Runtime.I
nteropServices: >= 4.1.0-rc3-24014-01
   - System.Net.Http 4.0.1-rc3-24008-00 requested package System.Runtime.Interop
Services: >= 4.1.0-rc3-24008-00
   - System.Reflection.Metadata 1.3.0-rc2-23911 requested package System.Runtime
.InteropServices: >= 4.0.21-rc2-23911
   - System.Xml.ReaderWriter 4.0.11-rc3-24001-00 requested package System.Runtim
e.InteropServices: >= 4.1.0-rc3-24001-00

The process is taking longer than expected.
Paket may still find a valid resolution, but this might take a while.
  Could not resolve package System.Runtime.InteropServices:
   - Dependencies file requested package System.Runtime.InteropServices: 4.1.0-r
c2-23911 (no prereleases)
   - System.IO.Compression 4.1.0-rc3-24014-01 requested package System.Runtime.I
nteropServices: >= 4.1.0-rc3-24014-01
   - System.Net.Http 4.0.1-rc3-23923 requested package System.Runtime.InteropSer
vices: >= 4.1.0-rc3-23923
   - System.Reflection.Metadata 1.3.0-rc2-23911 requested package System.Runtime
.InteropServices: >= 4.0.21-rc2-23911
   - System.Xml.ReaderWriter 4.0.11-rc3-24001-00 requested package System.Runtim
e.InteropServices: >= 4.1.0-rc3-24001-00

The process is taking longer than expected.
Paket may still find a valid resolution, but this might take a while.
Ctrl-C

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/fsprojects/Paket/issues/1610>

**Comment by forki** [comment]
mhm. even with strategy:min (which Nuget's default) it doesn't find a valid resolution. In short timespan. 

    source https://www.myget.org/F/dotnet-core/api/v3/index.json
    source https://www.nuget.org/api/v2/
    strategy: min

I assume there is in fact no valid resolution (looks one of packages needs System.Compression and there is only a RC3 version of it and that's incompatible to other stuff).

If we open the version restrictions like the following then paket has no issues to find a vlid resolution:

    source https://www.myget.org/F/dotnet-core/api/v3/index.json
    source https://www.nuget.org/api/v2/
    
    nuget Microsoft.NETCore.Platforms prerelease
    nuget NETStandard.Library prerelease 
    nuget System.Collections.Immutable prerelease
    nuget System.Diagnostics.Process prerelease
    nuget System.Diagnostics.TraceSource prerelease
    nuget System.Linq.Expressions prerelease   
    nuget System.Linq.Queryable prerelease   
    nuget System.Net.Requests prerelease  
    nuget System.Reflection.Emit prerelease  
    nuget System.Reflection.Emit.ILGeneration prerelease 
    nuget System.Reflection.Metadata prerelease
    nuget System.Reflection.TypeExtensions prerelease   
    nuget System.Runtime.InteropServices prerelease 
    nuget System.Runtime.InteropServices.PInvoke prerelease
    nuget System.Runtime.Loader prerelease
    nuget System.Security.Cryptography.Algorithms prerelease
    nuget System.Security.Cryptography.Primitives prerelease 
    nuget System.Threading.Tasks.Parallel prerelease 
    nuget System.Threading.Thread prerelease    
    nuget System.Threading.ThreadPool prerelease  
    nuget Microsoft.DiaSymReader.PortablePdb prerelease 
    nuget Microsoft.DiaSymReader prerelease

**Comment by dsyme** [comment]
OK, thanks.  I'll close for now. I somehow suspect these might indicate recurring problems, where people take an existing project.json and try to use Paket over the same dependencies.

**Comment by dsyme** [comment]
@forki Just to mention that although the resolution did go through, it resolved to a bunch of packages using the ``netstandard1.0``, ``netstandard1.3`` and ``netstandard1.5`` monikers, which Paket doesn't yet understand.  

So a big :+1: to [adding support for the netstandard monikers](https://github.com/fsprojects/Paket/pull/1605) :)

**Comment by forki** [comment]
Yeah we will add that. And next week they will make that obsolete again
like they did with DNX ;-)

Just kidding.
Obviously.
I hope.

;-)

**Comment by dsyme** [comment]
@forki I think netstandard is going to stick.
