### ISSUE TITLE
Some package versions aren't visible to paket

### ISSUE THREAD

**Issue by davidschwegler** [fsprojects/Paket#1629]
We have an internal nuget server, and for some packages not all the versions are showing up when running the `outdated` or `find-package-versions commands`, nor do they work with non-pinned dependency versions ( >= xxx). However, they *do* work when pinned, when specifying `outdated --pre` or `outdated --ignore-constraints`. They are not prerelease -- nuget (and Visual Studio) shows them as stable.

Example:
For package Logos.Documents.Contracts, the latest version is 6.1.0.165.
Proof: 
![image](https://cloud.githubusercontent.com/assets/4198124/14660446/4bcd9a54-065a-11e6-960a-e2a8b7b5973d.png)

Problem 1: Paket thinks the latest is 6.1.0.99
![image](https://cloud.githubusercontent.com/assets/4198124/14660488/8e9369b8-065a-11e6-879c-e99daf38a203.png)

Problem 2: paket breaks if I try to specify a min version: >= 6.1.0.108
![image](https://cloud.githubusercontent.com/assets/4198124/14660508/b7e066fe-065a-11e6-8ba1-12d807ffb542.png)

Even still, it installs and processes fine when pinned to 6.1.0.108
![image](https://cloud.githubusercontent.com/assets/4198124/14660518/ef13b82e-065a-11e6-8d3f-9eb4e5fdf785.png)
![image](https://cloud.githubusercontent.com/assets/4198124/14660661/1929a3ca-065c-11e6-84c9-37c67f7b0a86.png)

It also finds the latest version if I specify `outdated --pre` or `outdated --ignore-constraints`
![image](https://cloud.githubusercontent.com/assets/4198124/14660605/a91a97a6-065b-11e6-8786-2139419eb0fb.png)
![image](https://cloud.githubusercontent.com/assets/4198124/14660610/b6bdcc98-065b-11e6-9641-ba2c9716eafd.png)

Edit: For clarity, I'm specifying my local package source like so
![image](https://cloud.githubusercontent.com/assets/4198124/14660783/15a62ba0-065d-11e6-9c92-0cd4ded3f884.png)

Help! Is this a bug with Paket or user-error? :)

Thanks!

**Comment by kevinbosman** [comment]
You haven't specified what exactly you're using for your internal NuGet server, but for completeness this is a known reported issue with ProGet when querying available versions for a package. ProGet only returns the 1st 100 packages found, not necessarily in any particular order. If there are more than 100 versions of a particular package available on NuGet, Paket will fail to resolve correctly due to the way it needs to calculate version matches. They haven't implemented passthrough paging when nuget.org returns more than 1 page of results.

This problem was first reported to them 2 years ago, so it is unlikely to be fixed anytime soon.

**Comment by forki** [comment]
What? Pagination is in for very very long time. But maybe we gave s bug here.

**Comment by forki** [comment]
If you give me temporary access to your feed + send me the dependencies file then I will fix it ASAP. 
Sforkmann at gmail

**Comment by davidschwegler** [comment]
Thanks, emailed for follow-up.

**Comment by davidschwegler** [comment]
My apologies, our Klondike version was very old. I upgraded to v2 and the problem has been fixed.

:panda_face:
