### ISSUE TITLE
Suggestion: Lightweight Paket Restore

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/Paket#1640]
I'm thinking of projects - particuarly in a CI context - that simply need to do a paket restore, nothing more. Is there value in either incorporating that into the Bootstrapper (maybe not) or have a "lightweight" paket which can just do the restore.

With all the GitHub features in Paket 3 maybe it's not easily doable, don't know.

**Comment by smoothdeveloper** [comment]
@isaacabraham what is the current issue with "heavy-weight" paket?

I'm thinking also that after ilmerge, there is maybe possibility via some tool to cut all unused IL.

I never tried it but there is a .net binary packer also: http://rpx.codeplex.com/

**Comment by isaacabraham** [comment]
There's no massive issue - and I'm not saying Paket is "heavy weight" :-) I was more thinking on low bandwidth environments etc. it might be useful as a way to improve the speed of a restore rather than downloading the full Paket.

It's only 4mb or so though - I was more thinking aloud than anything really.

Perhaps this issue is a non starter and should be closed...

**Comment by smoothdeveloper** [comment]
maybe the issue is a good place to investigate binary packer?

I think in lowbandwidth environment, the actual process of checking packages on network takes longer than getting new paket once in a while.

I'm using a windows network share through a slow connection as a nuget source and every `paket install` is very slow, I wonder if there is a paket feature already which would help me?

**Comment by forki** [comment]
In a world where restore downloads the internet I don't really care about the 4MB.
