### ISSUE TITLE
Cannot add references to project

### ISSUE THREAD

**Issue by halcwb** [fsprojects/Paket#1655]
### Description

Probably not a bug, but more of a newbie question.

I have added references to the dependencies file and project references file. However running paket install, update or restore doesn't add the references to the project as specified by the references file.

### Repro steps

As described above.

### Expected behavior

Expect the references as specified in the paket.references file to be added to the project and visible in the VS 2013 references folder.

### Actual behavior

References are not added.

### Known workarounds

?

### Related information 

* Windows7
* VS 2013 F# project

**Comment by halcwb** [comment]
Ah, found a work around, I have to manually delete the installation dummy file. But wouldn't it be easier if paket cross checks the references file with the proj file to see if all references are installed?

**Comment by forki** [comment]
What Installation dummy file?

**Comment by halcwb** [comment]
When I run paket install,  an InstallationDummyFile.txt appears in the root folder of the project. When I change the paket.references file and run paket install again, nothing happens, but if I first remove the InstallationDummyFile.txt then the changes are applied.

**Comment by halcwb** [comment]
P.s. this is something I found in the proj file:

     <Content Include="InstallationDummyFile.txt">
       <Paket>True</Paket>
     </Content>

So, it seems to affect paket?

**Comment by halcwb** [comment]
Well totally confused now, cannot reproduce the problem anymore. But it definitely was there.

**Comment by smoothdeveloper** [comment]
@halcwb could you share `paket.dependencies` with us?

**Comment by halcwb** [comment]
Looks like this:

```
source https://nuget.org/api/v2

// group build

nuget FSharp.Formatting
nuget Fake
nuget SourceLink.Fake
nuget Newtonsoft.Json

github fsharp/FAKE modules/Octokit/Octokit.fsx

// group project

nuget FSPowerPack.Community

// group test

nuget FsUnit
nuget NUnit ~> 2
nuget NUnit.Runners ~> 2
nuget Unquote
nuget FsCheck
nuget FsCheck.NUnit
```

P.s. The source code is on github: http://github.com/halcwb/GenUnits.git.

**Comment by smoothdeveloper** [comment]
@halcwb thanks.

I see that some nuget packages contain this installationdummyfile.txt maybe some of those in your dependencies have this file.

https://danlimerick.wordpress.com/2011/10/01/getting-around-nugets-external-package-dependency-problem/

I think this file is harmless but paket will add this to your project probably the same way nuget would do it.

FSPowerPack.Community contains such a file.

**Comment by forki** [comment]
I assume this is related to "--hard" install option. In paket 2 we skip
installation for packages that already have files installed manually.
Unless you specify --hard.

This causes some confusion and we decided to make --hard the default for
paket 3. Actually it will be the only option in the future.
On Apr 30, 2016 7:16 PM, "Gauthier Segay" <notifications@github.com> wrote:

@halcwb <https://github.com/halcwb> thanks.

I see that some nuget packages contain this installationdummyfile.txt maybe
some of those in your dependencies have this file.

https://danlimerick.wordpress.com/2011/10/01/getting-around-nugets-external-package-dependency-problem/

I think this file is harmless but paket will add this to your project
probably the same way nuget would do it.

FSPowerPack.Community contains such a file.

—
You are receiving this because you commented.

Reply to this email directly or view it on GitHub
<https://github.com/fsprojects/Paket/issues/1655#issuecomment-215979803>
