### ISSUE TITLE
Major bug: Paket adds native references to .vcxproj file as if they are managed references (assemblies)

### ISSUE THREAD

**Issue by konste** [fsprojects/Paket#1658]
In paket.dependencies we have 
`framework: native`
`content: none`
`redirects: off`
`source https://www.nuget.org/api/v2/`
`nuget boost_date_time-vc140 1.60.0.0`
`nuget boost_filesystem-vc140 1.60.0.0`
`nuget boost_system-vc140 1.60.0.0`

And in paket.references same packages also designated as native:
`cpprestsdk.v140.winxp.msvcstl.static.rt-dyn framework: native`
`boost_filesystem-vc140 framework: native`
`boost_date_time-vc140 framework: native`
`boost_system-vc140 framework: native`

When Packet Install executes it adds references to .vcxproj file, but does it like that:
```xml
<When Condition="'$(Platform)'=='Win32'">
      <ItemGroup>
        <Reference Include="boost_date_time-vc140-mt-1_60">
          <HintPath>..\..\packages\boost_date_time-vc140\lib\native\address-model-32\lib\boost_date_time-vc140-mt-1_60.dll</HintPath>
          <Private>True</Private>
          <Paket>True</Paket>
        </Reference>
        <Reference Include="boost_date_time-vc140-mt-gd-1_60">
          <HintPath>..\..\packages\boost_date_time-vc140\lib\native\address-model-32\lib\boost_date_time-vc140-mt-gd-1_60.dll</HintPath>
          <Private>True</Private>
          <Paket>True</Paket>
        </Reference>
      </ItemGroup>
    </When>
```
What is wrong in that fragment is that `Reference` element should instead be `NativeReference` or it confuses build system badly as it expect References to be proper .NET assemblies.

Should be relatively easy and straightforward fix, but it is blocking use from further development with Paket. 

Konstantin

**Comment by forki** [comment]
Can you please come up with a small repro that has this issue and a csproj
that is fixed.

BTW: it's not a major bug it's just not really supported,  yet. ;-) but I
will do my best to help you with that.
On May 3, 2016 9:55 PM, "Konstantin Erman" <notifications@github.com> wrote:

In paket.dependencies we have
framework: native
content: none
redirects: off
source https://www.nuget.org/api/v2/
nuget boost_date_time-vc140 1.60.0.0
nuget boost_filesystem-vc140 1.60.0.0
nuget boost_system-vc140 1.60.0.0

And in paket.references same packages also designated as native:
cpprestsdk.v140.winxp.msvcstl.static.rt-dyn framework: native
boost_filesystem-vc140 framework: native
boost_date_time-vc140 framework: native
boost_system-vc140 framework: native

When Packet Install executes it adds references to .vcxproj file, but does
it like that:

<When Condition="'$(Platform)'=='Win32'">
      <ItemGroup>
        <Reference Include="boost_date_time-vc140-mt-1_60">
          <HintPath>..\..\packages\boost_date_time-vc140\lib\native\address-model-32\lib\boost_date_time-vc140-mt-1_60.dll</HintPath>
          <Private>True</Private>
          <Paket>True</Paket>
        </Reference>
        <Reference Include="boost_date_time-vc140-mt-gd-1_60">
          <HintPath>..\..\packages\boost_date_time-vc140\lib\native\address-model-32\lib\boost_date_time-vc140-mt-gd-1_60.dll</HintPath>
          <Private>True</Private>
          <Paket>True</Paket>
        </Reference>
      </ItemGroup>
    </When>

What is wrong in that fragment is that Reference element should instead be
NativeReference or it confuses build system badly as it expect References
to be proper .NET assemblies.

Should be relatively easy and straightforward fix, but it is blocking use
from further development with Paket.

Konstantin

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/fsprojects/Paket/issues/1658>

**Comment by konste** [comment]
Ok, working on it.

**Comment by konste** [comment]
Trivial example is here: https://goo.gl/5Uxjjx 
It is empty C++ project with a couple boost packages added with Paket. 
When you build it you get warnings 
`1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3246: Resolved file has a bad image, no metadata, or is otherwise inaccessible. Could not load file or assembly 'boost_filesystem-vc140-mt-1_60.dll' or one of its dependencies. The module was expected to contain an assembly manifest.`
That's exactly because Paket used Reference instead of NativeReference for native er-r... reference :)

**Comment by forki** [comment]
![image](https://cloud.githubusercontent.com/assets/57396/15015022/bc6fda5a-1209-11e6-9c59-a7eee81c0c8e.png)

does this look correct?

**Comment by konste** [comment]
If it compiles - it is probably fine! Frankly I also don't have a ton of experience with native NuGet packages. Playing by the ear. :)

**Comment by forki** [comment]
I don't know if it compiles - I'm missing some C++ build tools. I will just release this in v3 channel so you can test.

**Comment by konste** [comment]
Is there a build for me to try?

**Comment by forki** [comment]
I wish. Deutsche Telekom killed my Internet and tethering did not work...

I will let you know

**Comment by forki** [comment]
push succeeded please test latest paket 3.0 beta version. thx

**Comment by konste** [comment]
It does the right thing, but I cannot test it beyond the very first project, because https://github.com/fsprojects/Paket/issues/1657 is in the way. I have provided a small repro for that issue.

**Comment by forki** [comment]
yeah. hopefully I can take a look tomorrow. Developing a package manager without good internet connection is no fun.
