### ISSUE TITLE
Regression: Paket 3 fails to install or restore nuget package "Costura.Fody"

### ISSUE THREAD

**Issue by konste** [fsprojects/Paket#1662]
[NoCostura.zip](https://github.com/fsprojects/Paket/files/249742/NoCostura.zip)

Repro project attached. This is empty C# console app which pulls two packages: Fody and Costura.Fody. For unknown reason it does not download package "Costura.Fody". Version 2.63.3 downloads it just fine. This is major regression, please address.

Konstantin

**Comment by forki** [comment]
WTF!?

**Comment by konste** [comment]
I'm curious too :-)

**Comment by forki** [comment]
It's extracting it, but Garbage Collection is deleting it again. Fix should be ready soon.

**Comment by konste** [comment]
What's special about that package that it is the only one affected out of hundreds we reference?

**Comment by forki** [comment]
lol. the nuspec in the costura.fody package is wrongly named and confuses Paket.

![image](https://cloud.githubusercontent.com/assets/57396/15042718/a9583ae4-12c6-11e6-9d2f-86627ef36b95.png)

**Comment by konste** [comment]
It did not confuse 2.x
BTW I could not find what's the major difference between Paket 2.x and 3.x branches. Do you have a link?

**Comment by forki** [comment]
there is no garbage collection in 2.x

**Comment by konste** [comment]
https://fsprojects.github.io/Paket/reference/paket-garbagecollection.html gives me 404 :(

**Comment by forki** [comment]
if you diff master against v3 branch you will see HUGE differences. But release notes show most important things.

#### 3.0.0-beta030 - 05.05.2016
* Allow to reference git repositories - http://fsprojects.github.io/Paket/git-dependencies.html
* Allow to run build commands on git repositories - http://fsprojects.github.io/Paket/git-dependencies.html#Running-a-build-in-git-repositories
* Allow to use git repositories as NuGet source - http://fsprojects.github.io/Paket/git-dependencies.html#Using-Git-repositories-as-NuGet-source
* Additional local caches - http://fsprojects.github.io/Paket/caches.html
* Garbage collection in packages folder - https://github.com/fsprojects/Paket/pull/1491
* Allows to exclude dll references from a NuGet package - http://fsprojects.github.io/Paket/references-files.html#Excluding-libraries
* Allows to use aliases for libraries - http://fsprojects.github.io/Paket/references-files.html#Library-aliases
* Create Choose nodes for .NET Standard
* USABILITY: Removed "specs:" from paket.lock since it was copied from Bundler and had no meaning in Paket - https://github.com/fsprojects/Paket/pull/1608
* BREAKING CHANGE: Removed --hard parameter from all commands. Paket threads all commands as if --hard would have been set - https://github.com/fsprojects/Paket/pull/1567

404 is because of release process. Will be back in couple of minutes when the bugfix is pushed

**Comment by forki** [comment]
So I hope all your issues are fixed now. I'm pretty much offline until
Monday.

**Comment by konste** [comment]
Thanks a lot!
