### ISSUE TITLE
No include file is generated for GitHub dependencies

### ISSUE THREAD

**Issue by ChrSteinert** [fsprojects/Paket#1677]
### Description

No include script files are generated for dependencies downloaded from GitHub.

### Repro steps

1. Set up a "clean" Paket directory (following the steps from the getting started page).
2. Use the following paket.dependencies file:
```
github forki/FsUnit FsUnit.fs
```
3. Generate include scripts via the command `paket generate-include-scripts framework net46` (or any other framework version).

### Expected behavior

An include file for the downloaded dependency (like, in this case, a `*.fs`file) is generated.

### Actual behavior

No include files or folders are generated.

### Related information 

* Running Pre-release 3.0.0-beta036

**Comment by ChrSteinert** [comment]
Same goes for http dependencies as well, btw.

**Comment by smoothdeveloper** [comment]
@ChrSteinert I'm not sure if we intend to support this, at least the documentation states:

> It is possible to generate include scripts for all registered NuGet packages defined in the paket.dependencies file.

http://fsprojects.github.io/Paket/paket-generate-include-scripts.html

Do you think there is a value of generating an include file for a single .fs file in your case? The same .fs file might fail to include since it might depend on other dependencies (nuget packages) being loaded but paket won't have any ways to guess that.

**Comment by ChrSteinert** [comment]
That's right. You might not know of any other dependencies. 
Still, it is convienient to only have to include scripts from one directory and not having to "manually" scan the paket-files folder for github/http dependencies. 
I see that this is a luxury issue and I personally won't profit from this beeing "fixed". Still wanted to raise the discussion.

**Comment by smoothdeveloper** [comment]
@ChrSteinert got it, thanks.

If this gets implemented, it also needs to take care of not importing `.fs` file in `.csx` and the converse, probably few other things I can't think of yet would need to be taken care as well.

Yes for me it is not too high importance, I guess because the individual files still end up with a natural URI and there is no concept of transitive dependencies (which was major reason to implement the feature for nuget packages).

@forki should we put enhancement and up-for-grabs labels for now?

**Comment by matthid** [comment]
I don't think we should not even support this because of the reasons already mentioned by @smoothdeveloper. Currently we don't care if we generate `f#` or `c#` include scripts. IMHO it should stay this way. I don't think adding some special cases for this feature adds a lot of value.

However, for github (v3) dependencies paket can pull the repository, build it and reference the newly build nuget package. Do we support that already with 'generate-include-scripts' because of the paket API (ie. is that transparent to us)? If not we probably should. If we do, I think we should close this issue.

**Comment by ChrSteinert** [comment]
I guess this is 'as designed' then.
