### ISSUE TITLE
Question: 'paket install' remove 'bindingRedirect' from Web.config

### ISSUE THREAD

**Issue by rdcm** [fsprojects/Paket#2178]
### Description

After 'paket install', paket remove 'bindingRedirect' sections from Web.config.
Removed sections - http://pastebin.com/scHi0Rpy

### Repro steps

Invoke 'paket install'.

### Expected behavior

Successful application build and start.

### Actual behavior

Successful application build, but when app start in browser i see exception:

Could not load file or assembly 'System.Web.Http, Version=5.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Calling assembly : Ninject.Web.WebApi.OwinHost, Version=3.2.0.0, Culture=neutral, PublicKeyToken=c7192dc5380945e7.

If discard changes in Web.config, application successful started.
Situation will be repeated if invoke 'paket install', section will be removed, apllication will not start.

### Known workarounds

.NET 4.6.1, WebApi project

I'm not sure if this is bug. Can i solve this problem by adding some configs or run paket commands?

**Comment by forki** [comment]
Usually you control binding redirects in the paket.dependencies file. Try
"nuget XYZ redirects:force" and run install again.

Am 07.03.2017 17:16 schrieb "Timofey Myagkikh" <notifications@github.com>:

Description

Afetr 'paket install', paket remove 'bindingRedirect' sections from
Web.config.
Removed sections - http://pastebin.com/scHi0Rpy
Repro steps

Invoke 'paket install'.
Expected behavior

Successful application build and start.
Actual behavior

Successful application build, but when app start in browser i see exception:

Could not load file or assembly 'System.Web.Http, Version=5.0.0.0,
Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its
dependencies. The located assembly's manifest definition does not match the
assembly reference. (Exception from HRESULT: 0x80131040)

Calling assembly : Ninject.Web.WebApi.OwinHost, Version=3.2.0.0,
Culture=neutral, PublicKeyToken=c7192dc5380945e7.

If discard changes in Web.config, application successful started.
Situation will be repeated if invoke 'paket install', section will be
removed, apllication will not start.
Known workarounds

.NET 4.6.1, WebApi project

I'm not sure if this is bug. Can i solve this problem by adding some
configs or run paket commands?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/fsprojects/Paket/issues/2178>, or mute the thread

**Comment by rdcm** [comment]
redirects: on - solve my problem
