### ISSUE TITLE
Running paket install installs .pdb files

### ISSUE THREAD

**Issue by JohanLarsson** [fsprojects/Paket#2219]
### Description

When running `paket install` with .pdb files in `packages\analyzers\SomeAnalyzer\analyzers\dotnet\cs\SomeAnalyzer.pdb` the pdb file is added as references to the projects.

Also if I remember correctly analyzers are uninstalled from the project if the folder is empty. Maybe this is the intended behavior.

### Repro steps

1. Create a C# project and add [an analyzer nuget](https://www.nuget.org/packages/Gu.Analyzers/)
2. Add a pdb file to `packages\analyzers\SomeAnalyzer\analyzers\dotnet\cs\SomeAnalyzer.pdb`
3. Run paket install

[ConsoleApp1.zip](https://github.com/fsprojects/Paket/files/891139/ConsoleApp1.zip)

### Expected behavior

I don't expect `paket install` to install anything that is not in the .nupkg

**Comment by JohnyWS** [comment]
Hmm, it seems this has been reintroduced again. :-/

I've tracked it down to 809513c which was a pretty big refactoring. It now respects completely what is in the nuspec file, however, that now conflicts with analyzers again.

Current issue for me, is when attempting to use https://www.nuget.org/packages/FakeItEasy.Analyzer.CSharp/ - version 5.2.0 has a /analyzers/dotnet/cs/FakeItEasy.Analyzer.CSharp.pdb file included, which is then added to the csproj files, which introduces compiler errors.

I'm not sure as to what is the proper way to fix it though, since the context of the original fix is gone, and I'm not sure having a global exclude pattern is the correct way to go? (e.g. exclude anything BUT *.dll when the path begins with "analyzers")

**Comment by JohnyWS** [comment]
@vbfox have you encountered the error yourself, since you introduced the fix?

**Comment by JohnyWS** [comment]
Current workaround for us, is to include a custom msbuild step that removes the pdb files from Analyzers. Will return with more details when I'm back at my office desk. :)

**Comment by vbfox** [comment]
@JohnyWS no didn't encounter the error. We have everything including paket pinned and only update it every ~6months but should have the commit you pointed to as we currently pin `5.195.7`

We also reference a single analyzer currently and don't have anything in dotnet core (only normal FW) so the fact we don't see the problem doesn't mean that it doesn't exists.

**Comment by JohnyWS** [comment]
@vbfox Thank you for the feedback. :) I'm pretty certain the bug has been reintroduced though, so I'll see if I can get it corrected again somehow.

@matthid do you have any input as to how this can be achieved? I'm not entirely sure as what should be the correct approach here, as it just feels wrong to hardcode exclusions like I hint at. Do you have a better idea?

**Comment by matthid** [comment]
@JohnyWS in the linked commit some new tests were introduced, can you try to come up with a new test for your scenario so it might be easier to understand the issue?

**Comment by JohnyWS** [comment]
@matthid sure! I'll try to see if I can get the test running locally - won't be until, at the earliest, next week though, but I'll get back. :)

**Comment by JohnyWS** [comment]
@matthid do you have a guide on how to run the tests? I can neither make it work with VS Code nor VS. The build.cmd works fine, but VS can only find the tests in "Paket.Bootstrapper.Tests" and the only guides I could find to run F# tests via VS Code used other test libraries.. :-/

**Comment by matthid** [comment]
@JohnyWS Usually I'm using the VS Test explorer but it breaks from time to time. In any case, afaik you need to use VS 2017. If that doesn't work I usually try to run a single test via command line and work from there.
