### ISSUE TITLE
Paket v4 fails update cmd (infinite dependency loop ?)

### ISSUE THREAD

**Issue by MrLuje** [fsprojects/Paket#2225]
### Description

I have a solution where paket (4.3.0 at this time) fails the update command, it never ends
whereas with paket 3.36, it finished in 4s

### Repro steps

Not ATM, reproduced with a private repo, I will try to provide something if I can pinpoint the issue

### Expected behavior

Paket update should finish in a reasonable amount time

### Actual behavior

I stopped the update after 30 min
I attached a filtered verbose output for both v3 & v4 paket.exe

[v4_res.txt](https://github.com/fsprojects/Paket/files/909697/v4_res.txt)
[v3_res.txt](https://github.com/fsprojects/Paket/files/909698/v3_res.txt)

You can see that v4 seems lost in the dependency graph, not sure if caused by a circular dependency but the thing is it was working fine with v3

### Known workarounds

Stick with v3 for this solution 😢

**Comment by forki** [comment]
Yes please provide a repro. We are very interested in fixing this

Am 10.04.2017 12:11 nachm. schrieb "MrLuje" <notifications@github.com>:

Description

I have a solution where paket (4.3.0 at this time) fails the update
command, it never ends
whereas with paket 3.36, it finished in 4s
Repro steps

Not ATM, reproduced with a private repo, I will try to provide something if
I can pinpoint the issue
Expected behavior

Paket update should finish in a reasonable amount time
Actual behavior

I stopped the update after 30 min
I attached a filtered verbose output for both v3 & v4 paket.exe

v4_res.txt <https://github.com/fsprojects/Paket/files/909697/v4_res.txt>
v3_res.txt <https://github.com/fsprojects/Paket/files/909698/v3_res.txt>

You can see that v4 seems lost in the dependency graph, not sure if caused
by a circular dependency but the thing is it was working fine with v3
Known workarounds

Stick with v3 for this solution 😢

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/fsprojects/Paket/issues/2225>, or mute the thread

**Comment by MrLuje** [comment]
You can check https://github.com/MrLuje/Paket-v4-update-issue

I was not able to properly reproduce it so I integrated the same dependency graph we currently have on our private repo (as a local repository in the sln)

We found the cause : MassTransit & StackExchange.Redis have some incompatible versions (we can see this in verbose output) but it should be able to stop crawling the packages 😄

**Comment by MrLuje** [comment]
In the end, duplicate of #2289 and also fixed by PR #2299
Great job, can't wait to see this officially released !
