### ISSUE TITLE
paket doesn't evaluate compliant .net standard library target runtimes properly

### ISSUE THREAD

**Issue by cloudRoutine** [fsprojects/Paket#2245]
![](http://i.imgur.com/Sbo9E54.png)

According to the .NET platform support chart, packages targeting netstandard13 should install into projects targeting net46+ 

Paket used to install packages properly in this situation

![](http://i.imgur.com/5zDT8cv.png)

But now it no longer does.

Repro -

[frameworkfail.zip](https://github.com/fsprojects/Paket/files/919638/frameworkfail.zip)

**Comment by matthid** [comment]
This issue is interesting because there are at least two meanings of how you can understand the `framework: netstandard13` syntax:

1. "Paket, I use this package only for compiling against the specific framework. Get rid of all the stuff I don't need"
2. "Paket, use the package as if it would contain only the contents of the given framework and continue normally"

You assumed 2 while 1 is implemented. From a resolving standpoint there is not much difference as both restrict the number of dependency groups used.
From an installing standpoint there is difference: In "1" we simply ignore everything but the given frameworks.
In "2" we would need add the restrictions, and then add back all compatible frameworks for the remaining folders...
Hope this makes sense :)

As this more a philosophical question as implementation we should discuss which behavior makes more sense, or if we should add "2" with another feature. /discuss /cc @forki

**Comment by cloudRoutine** [comment]
if VFT just supported targeting netstandard this wouldn't be an issue, so there really isn't a need for a new feature or additional complexity. it's just an unfortunate situation until VFT gets up to snuff 😞
