### ISSUE TITLE
Paket netcore problems with custom NuGet Feeds 

### ISSUE THREAD

**Issue by matthid** [fsprojects/Paket#2262]
### Description

I have added a custom NuGet feed on `paket.dependencies` and use a Paket from there.
This works on windows as we put the package into the NuGet cache.
On travis this seems to fail https://travis-ci.org/fsharp/FAKE/builds/223757642

We probably miss the correct Cache folder NuGet is using there..

Note: I found a different error when using local feeds. We don't put them in the Cache either and we get a similar error on windows.

### Repro steps

Add a package (for example from an Appveyor feed) to a netcore project.

1. Try to build on Unix/Travis

### Expected behavior

Should work.

### Actual behavior

NuGet fails to restore.

### Known workarounds

...

**Comment by matthid** [comment]
@julkwiec yes I warned from this scenario, see my comment in https://github.com/fsprojects/Paket/issues/2676

**Comment by julkwiec** [comment]
I'll check tomorrow if renaming the package folder that was created by Paket in the cache will make it visible for NuGet.

What is the reason behind lowercasing package names in the filesystem?

**Comment by julkwiec** [comment]
I've created a repo with a test scenario:
https://github.com/julkwiec/paket-dotnet-docker-test

Looks like `dotnet restore` is lowercasing package names, while `paket restore` is not. Also, simply renaming package folder in cache (`~/.nuget/packages`) doesn't help.

**Comment by julkwiec** [comment]
I've managed to capture all changes made by Paket and dotnet to the container filesystem:
https://github.com/julkwiec/paket-dotnet-docker-test/blob/master/logs/dotnet.layer.tar
https://github.com/julkwiec/paket-dotnet-docker-test/blob/master/logs/paket.layer.tar

Besides different casing of package names in `/root/.nuget/packages`, the content of `/root/.local/share/NuGet` is different as well (also note different folder casing: `NuGet` vs `Nuget`).

I'll have a closer look later, feel free to check it out.

**Comment by julkwiec** [comment]
Lowercasing the names of package folder and package files did the trick.

### Repro steps (Windows + Docker)
1. Checkout https://github.com/julkwiec/paket-dotnet-docker-test
2. Open powershell, run `run.ps1`
3. In the container, run `dotnet restore --source /empty` - it will fail since the package source directory is empty and AutoMapper is not yet present in the cache.
4. Run `mono paket.exe restore`
5. Run `dotnet restore --source /empty` again - dotnet still doesn't find the package in cache
6. Lowercase the names of AutoMapper files and directories:
  - `cd ~/.nuget/packages`
  - `mv AutoMapper automapper`
  - `cd automapper/6.1.1/`
  - `mv AutoMapper.6.1.1.nupkg automapper.6.1.1.nupkg`
  - `mv AutoMapper.6.1.1.nupkg.sha512 automapper.6.1.1.nupkg.sha512`
  - `mv AutoMapper.nuspec automapper.nuspec`
7. Run `cd /test`
8. Run `dotnet restore --source /empty`. No failure this time - package was found in cache.

**Comment by julkwiec** [comment]
Could this issue be closed?
https://github.com/fsprojects/Paket/pull/2826
