### ISSUE TITLE
Paket is failing to bring Libuv into .net 451 project

### ISSUE THREAD

**Issue by tsibelman** [fsprojects/Paket#2277]
### Description
I working with latest paket 4.8.0

When I add Libuv package to my project paket.references that is developed in 4.5.1  and run paket install I get following error 

"Package Libuv contains libraries, but not for the selected TargetFramework net451 in project"

You can see attached repro
[PaketWithProblem.zip.txt](https://github.com/fsprojects/Paket/files/954179/PaketWithProblem.zip.txt)

I think it caused by incorrect interpretation of dependency of .NETStandard 1.0

**Comment by matthid** [comment]
Runtime support will be added soon, stay tuned. Can you test what NuGet does with that package in net451?

**Comment by tsibelman** [comment]
Thank you I will check what NuGet doing , when do you think runtimes would be supported ?

**Comment by matthid** [comment]
> Thank you I will check what NuGet doing 
Yes please :)
>  when do you think runtimes would be supported 
After https://github.com/fsprojects/Paket/pull/2267 is merged which can take a while. To be clear, currently it is only supported in a dotnet sdk world. Legacy applications will not be changed because I have no idea how NuGet behaves on old projects. But I'm pretty sure we can add that easily once we know that.
