### ISSUE TITLE
Version information in paket.dependencies is ignored

### ISSUE THREAD

**Issue by pmbanka** [fsprojects/Paket#2290]
### Description
[Docs say](https://fsprojects.github.io/Paket/dependencies-file.html#Required-Paket-version) it should be possible to pin Paket version. This setting seem to be ignored.

### Repro steps

1. Clone https://github.com/pmbanka/paket-version-repro
2. Run bootstrapper, then `paket install`
3. Observe that latest Paket version is used

### Expected behavior

Paket version specified in `paket.dependencies` is used.

### Actual behavior

Last Paket version is used.

**Comment by forki** [comment]
cc @vbfox

**Comment by vbfox** [comment]
A few things here :
* Your're using an old version of the boostrapper (**2.41.0**) but the version pinning was first implemented in **3.25.0**
* If you take the latest boostrapper (**4.x**) you can't pin the version you specify (**3.24.1**) as it's before the sha256 file was introduced and new boostrapper expect this file to exist
* Even with version **3.25.0** of the bootstrapper it wouldn't work for getting **3.24.1**. The boostrapper would do it's job correctly but paket.exe would fail because it doesn't know that it need to ignore `version` lines.

So if you don't want to move to 4.x (I immagine due to #2289) I would suggest getting [3.25.0 bootstrapper](https://github.com/fsprojects/Paket/releases/tag/3.25.0) and pinning to that version.

Essentially, not a bug that issue can be closed 😸 

*PS(1): You have commited paket.exe in your repro but that's not necessary if you use the bootstrapper (But I guess it was just to demonstrate that the pinning didn't work here).*
*PS(2): **3.25.0** already supported magic mode, so you can rename the boostrapper binary to `paket.exe` and use it as-is, cool isn't it ?* 🦊

**Comment by pmbanka** [comment]
@vbfox thank you very much for the explanation. I did not think about versioning of the bootstrapper itself.

PS. yeah, I normally would not commit paket.exe, and yes the magic mode is indeed very cool 💯
