### ISSUE TITLE
Artifactory URLs are also reachable via jfrog.io

### ISSUE THREAD

**Issue by Larusso** [fsprojects/Paket#2339]
### Description

The pull request #2073 fixed the resolution of artifactory hosted nuget packages. Artifactory changed for hosted enterprise licenses the base url. The packages are reachable also via `jfrog.io`. The fact that one is also able to define custom host url's makes the fix in #2073 rather questionable. 

### Repro steps
Create a new empty project

1. create `paket.dependencies` file
2. add a `jfrog.io` source
3. add a dependency with a loose version constraint for it's dependencies

### Expected behavior
Paket resolved all dependencies to `max` version

### Actual behavior
Paket used the `min` version

### Known workarounds
Use `artifactoryonline.com` URL's instead

**Comment by forki** [comment]
Any chance you could extend the fix? Please send us a pull request if
possible. Thanks

Am 15.05.2017 8:21 nachm. schrieb "Manfred Endres" <notifications@github.com
>:

Description

The pull request #2073 <https://github.com/fsprojects/Paket/pull/2073>
fixed the resolution of artifactory hosted nuget packages. Artifactory
changed for hosted enterprise licenses the base url. The packages are
reachable also via jfrog.io. The fact that one is also able to define
custom host url's makes the fix in #2073
<https://github.com/fsprojects/Paket/pull/2073> rather questionable.
Repro steps

Create a new empty project

   1. create paket.dependencies file
   2. add a jfrog.io source
   3. add a dependency with a loose version constraint for it's dependencies

Expected behavior

Paket resolved all dependencies to max version
Actual behavior

Paket used the min version
Known workarounds

Use artifactoryonline.com URL's instead

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/fsprojects/Paket/issues/2339>, or mute the thread

**Comment by cdrnet** [comment]
@Larusso please also keep report the issue to jfrog. If more customers complain about this bug (which #2073 is just working around as good as possible) maybe they'll finally fix their broken feed implementation sometime...

**Comment by Larusso** [comment]
@forki I'm not super familiar with f# just scanned the source code for a reason why Paket is not picking up my nuget package version and saw the workaround. I don't know if it is feasible to add a second check against the `jfrog.io` hostname.

**Comment by matthid** [comment]
So this is basically external?

**Comment by cdrnet** [comment]
I'd argue it's internal. But the fix in #2073 itself seems to have regressed in the meantime. Unfortunately I still have not had time to investigate, report and fix properly (we keep using Paket v4.8.8 for the time being, which is fine).

**Comment by matthid** [comment]
Ok at the very least we need a new bug report, ideally we would like to see a regression test going forward ...

**Comment by cdrnet** [comment]
Yes. For regression tests we'll first need #2554 / #2511 though.
