### ISSUE TITLE
Add group info to .fsproj.references

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fsprojects/Paket#2373]
Related: https://github.com/fable-compiler/Fable/issues/960

Fable is now integrated with Fable and it works really well, thanks for your help! But it seems that the integration doesn't work with Paket groups yet. This shouldn't be difficult as we only need to add the group name (in lower case) after `packages` to build the package location. However, I don't know how to identify the group from the information that Fable currently reads from the `.fsproj.references` file. Would it be possible to add the group information there too (or specify an alternative way to get it)?

Notes:

- @matthid [proposed as a long term solution to use paket.core in fable to be able to use the api to get package folder paths and stuff](https://github.com/fable-compiler/Fable/issues/960#issuecomment-304141249). It's not necessary to compile Paket with Fable for this, as the integration only affects Fable .NET (Core) distribution. Though I'm a bit concerned about the size of the dependency to use a couple of helpers.

- On another note, is there also an easy way to detect the framework of the dependency so we can also build the path to the referenced .dll (`packages/[<group-name>]/<package-name>/lib/<framework>/<package-name>.dll`)?

**Comment by matthid** [comment]
> Though I'm a bit concerned about the size of the dependency to use a couple of helpers.

Why is that?

> On another note, is there also an easy way to detect the framework of the dependency so we can also build the path to the referenced .dll (packages/[<group-name>]/<package-name>/lib/<framework>/<package-name>.dll)?

Obviously again there is a paket-core api for that. What exactly are you looking for? Any specific framework or the highest one. Something else?
I'm really unsure about this request as this would put us back to a pre-dotnet-sdk world where we talk about individual references instead of packages.

**Comment by forki** [comment]
Fable should never depend on paket.core. That's just bringing a whole new world of pain. Let's extend the file

**Comment by matthid** [comment]
@forki Don't you feel its going the wrong direction here?
Rather then making paket more general use, we add more and more support into paket.
Paket knows about old and new project files and now fable. Should everything move into paket?
I'd rather have a stable API people can use and extend on, maybe (long term) even the current coupled stuff could use this API in the future (like a modular paket where "old-fsproj" is just one module building on a general API).

> That's just bringing a whole new world of pain. 

Can you elaborate? I agree that fable should not call restore or update or things like that, but on the other hand I don't get why we need a new file when `paket.references` and `paket.lock` have all the info fable needs...
Tbh. I see this new file more as a dotnetcore-integration-hack. And now another hack for fable was added on top. I'm really not feeling comfortable with this (without having concrete reasons atm).

Long term I think either Fable should provide an extension point where paket can dock into or the other way around.

**Comment by matthid** [comment]
Would a smaller library like `Paket.EcoSystem` which only contains parsers for the paket files and maybe some package analysis (parts of InstallModel) be more acceptable?

Or do you not like the idea at all?

I think that was one of the things I discussed with @cloudRoutine in the past already (so pinging him now ;)).

**Comment by forki** [comment]
This is going into general use directory. Paket is using this flat file as
well. It's not originally intended for fable. It just happens that it's
useful for fable as well.

Am 27.05.2017 2:54 nachm. schrieb "Matthias Dittrich" <
notifications@github.com>:

**Comment by alfonsogarciacaro** [comment]
Fast as lightning as always, @forki! Thanks a lot for this :clap: :clap: That should be enough to make Fable work with Paket groups. Just a couple of quick questions:

- Will the group names be always in lower case in the `.fsproj.references`?
- The way to build the path to the package is: `<paket.dependencies-dir>/packages/<group>/<package-name>`, right?
- If the group name is `main`, should I can omit `<group>` in the path above? ☝️ 

@matthid It may be me but I'm always wary of adding dependencies to my group unless I'm going to use the API extensively, especially for Fable where we are always considering the possibility of compiling to JS. But I understand (and share) your concerns about adding too many patches to Paket to support Fable. For the future, to avoid breaking Fable when something in Paket changes (like using .nuget cache instead of a local packages folder), maybe the way to go is to use @enricosada https://github.com/enricosada/dotnet-proj-info library to properly solve F# compiler arguments from .fsproj:

Fable > dotnet-proj-info > MSBuild > Paket > profit!

I was just a bit concerned about the MSBuild dependency because it caused some problems in past Fable versions, but hopefully the situation is improved with dotnet SDK :pray:

**Comment by forki** [comment]
* Will the group names be always in lower case in the .fsproj.references?
  - No, but I can do that

* The way to build the path to the package is: <paket.dependencies-dir>/packages/<group>/<package-name>, right?
  - yes except for main

* If the group name is main, should I can omit <group> in the path above?
  - you need to omit

**Comment by matthid** [comment]
That's why I think it's wrong, all those are implementation details of paket, fable shouldn't need to hardcode them. Again, I'm fine with this as a short term solution but I'm still not convinced that's the proper way to do things. Will try to come up with an alternative suggestion...

**Comment by alfonsogarciacaro** [comment]
@forki Don't worry, I can just add `.ToLower()` and be done :)

**Comment by enricosada** [comment]
#### about assemblies reference path

Afaik ask msbuild is not that bad meanwhile it is used as the project file (the `Fable > dotnet-proj-info > MSBuild` ) if i understand right your question: "get the assemblies references".
@alfonsogarciacaro I was expecting this was already how fable get fsc args, is not?

Anyway, that's how intellisense works ( `VS|FSAC -> msbuild` ), and how will continue to work (for new VS too), so is expected to continue work. The `dotnet-proj-info` as library just write the msbuild xml needed for you, instead of use msbuild automation (so you dont care about msbuild assemblies). And works for all msbuild host runtimes (msbuild/mono msbuild/dotnet cli).

@alfonsogarciacaro if you need anything about it, example try it in a spike, feel free to ping me.

#### About package directory:

For example, the package directory is saved (on restore) into `obj\{projectName}.{projectExt}.nuget.g.props` who contains:

```xml
<NuGetPackageRoot Condition=" '$(NuGetPackageRoot)' == '' ">e:\temp\lkjh\packages</NuGetPackageRoot>
```

And because that's imported as normal prop, asking msbuild to give me `$(NuGetPackageRoot )` will always give you the right package directory used (doesnt matter to what fsproj you ask). 
Should work the same with paket afaik (/cc @forki)
If paket does layout differently (so cannot override `NuGetPackageRoot `, can do the same, adding an `PaketPackageRoot` property for example.
Or not, and just use a convention.

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for the info @enricosada!

> @alfonsogarciacaro I was expecting this was already how fable get fsc args, is not?

No, at the moment Fable is doing [a custom simplistic resolution of the .fsproj](https://github.com/fable-compiler/Fable/blob/8b4c54b2b0467e9c7b95574c13ee29af68f6a621/src/dotnet/Fable.Tools/ProjectCracker.fs#L108). I started doing this in Fable 0.7 (with old project format) because the MSBuild dependency caused problems in some Windows machines. I'm planning to use your library in the near future to have better resolution of fsc args and not depending directly on Paket, although that would mean resolving the dependency tree by ourselves (to know the compilation order of all source files) , something Paket is doing for us right now 😄
