### ISSUE TITLE
Paket 5.1.0 can no longer find a resolution if packages are missing in some sources.

### ISSUE THREAD

**Issue by tsibelman** [fsprojects/Paket#2440]
### Description

We have two nuget sources local server and nuget.org 

For some reason Paket 5.0 write warning on every dependency he fails to find in one of the sources 

Here is a sample 
```
Failed to get package details 'unable to find entry node for package System.Reflection.Extensions 4.3.0 in <?xml version="1.0" encoding="utf-8" standa
lone="yes"?>
<feed xml:base="http://nuget/NugetForVS/nuget/" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/
ado/2007/08/dataservices/metadata" xmlns="http://www.w3.org/2005/Atom">
  <title type="text">Packages</title>
  <id>http://nuget/nugetForVS/nuget/Packages</id>
  <updated>2017-06-18T15:01:04Z</updated>
  <author>
    <name />
  </author>
  <link rel="self" title="Packages" href="Packages" />
</feed>'. This feeds implementation might be broken.
```

Can this warning to be removed ?

**Comment by matthid** [comment]
@tsibelman Can you provide more information?

So `http://nuget/` is the local nuget server?
Which nuget server is it because it seems to answer in a strange way.
Also can you attach the output of verbose mode (ie with `-v` parameter)

**Comment by tsibelman** [comment]
@matthid yes http://nuget/nugetForVS/nuget is our local server we use Microsoft NuGet.Server v2.11.2.0 https://www.nuget.org/packages/NuGet.Server/2.11.2 so it as vanilla as it can be 

You can see atached verbose log, it looks like you threating 404 as error

@
[log.txt](https://github.com/fsprojects/Paket/files/1083171/log.txt)

**Comment by Desarc** [comment]
We are seeing the same warnings towards our local NuGet server ([Inedo Proget 4.7.11](https://inedo.com/proget)) with version `5.0.0 =<` of Paket.

It seems to occur when we use more than one source in paket.dependencies, and Paket fails to resolve the package from one of the sources, like in the original post.

With version 5.0.0 this is not a blocker since package resolution succeeds anyway, but with version 5.1.0 it results in a failed package resolution because of conflicts.

**Comment by forki** [comment]
@matthid did we change something in that for 5.1?

**Comment by matthid** [comment]
Not that I'm aware of...
@Desarc can you please attach a full log as well (when package resolution fails). Additionally a small log could help we well.

**Comment by Desarc** [comment]
I ran the same package resolution with versions 4.8.8, 5.0.0 and 5.1.0 for comparison.

[paket_update_4.8.8.txt](https://github.com/fsprojects/Paket/files/1084673/paket_update_4.8.8.txt)
[paket_update_5.0.0.txt](https://github.com/fsprojects/Paket/files/1084677/paket_update_5.0.0.txt)
[paket_update_5.1.0.txt](https://github.com/fsprojects/Paket/files/1084693/paket_update_5.1.0.txt)

For the 5.1.0 run, I had to eventually just kill the process, because it seemed to get stuck in a loop. The first run i ended up with an 850MB log file, so the one included above is from a run where i killed it much quicker. There did not seem to be anything interesting in the log beyond that point anyway, just repeats of the same thing.

**Comment by matthid** [comment]
Ok I think there are multiple problems here:
 - First it seems the task prioritization is not working as it should as the request to Prism is timing out after 30 seconds
 - Second 5.0.0 is recovering later when the response has been finished, while 5.1 is "caching" the error -> therefore it never finishes

Probably both should be fixed. But it has noting to do with this issue (which is about the warning)

**Comment by matthid** [comment]
Sorry @tsibelman, I think @Desarc has stolen this issue now :P. I'll track the warning in https://github.com/fsprojects/Paket/pull/2441 while upgrading this issue to the 5.1 resolving problem (maybe I can fix both together maybe not).

**Comment by tsibelman** [comment]
@matthid I just hope you will not forget about me :)

**Comment by matthid** [comment]
Reopen for the warning :)
