### ISSUE TITLE
paket restore/install resulted in "The profile 'portable-net45+win8+wp8+wp81+wpa81' is not a known profile. Please tell the package author."

### ISSUE THREAD

**Issue by piotr07da** [fsprojects/Paket#2495]
### Description

In paket version **4.8.8** after paket install I have got this:

      Microsoft.AspNet.WebApi.Client (5.2.3)
      Microsoft.Net.Http (>= 2.2.22) - framework: portable-wp80+win+wp81+wpa81
      Newtonsoft.Json (>= 6.0.4) - framework: >= net45, portable-wp80+win+wp81+wpa81

And in this case paket restore returns no errors.

In paket version **5.0.0** after paket install I have got this:

      Microsoft.AspNet.WebApi.Client (5.2.3)
      Microsoft.Net.Http (>= 2.2.22) - restriction: && (< net45) (>= portable-net45+win8+wp8+wp81+wpa81)
      Newtonsoft.Json (>= 6.0.4) - restriction: >= portable-net45+win8+wp8+wp81+wpa81
And in this case paket restore returns:
"_The profile 'portable-net45+win8+wp8+wp81+wpa81' is not a known profile. Please tell the package author._" error.

Why this is not know profile? Is there way to solve this problem? Currently I installed 4.8.8 version.

### Repro steps

1. Create paket.dependencies with:

          nuget Microsoft.AspNet.WebApi 5.2.0
          nuget Microsoft.AspNet.WebApi.Client 5.2.3
          nuget Microsoft.AspNet.WebApi.Core 5.2.3
          nuget Microsoft.AspNet.WebApi.WebHost 5.2.3
          nuget Microsoft.Net.Http 2.2.22

2. Run paket install

**Comment by matthid** [comment]
The known profiles are listed in http://embed.plnkr.co/03ck2dCtnJogBKHJ9EjY
While we support others those are the well defined ones with separate reference assemblies installed.
We print a warning because using a different profile might indicate a packaging error.
Problematic package is https://www.nuget.org/packages/Microsoft.AspNet.WebApi.Client

It is not a paket bug, because nuget apparently can't associate the profile with a known profile either: http://nugettoolsdev.azurewebsites.net/4.0.0/parse-framework?framework=portable-net45%2Bwin8%2Bwp8%2Bwp81%2Bwpa81. Compare this with http://nugettoolsdev.azurewebsites.net/4.3.0-beta1-2418/parse-framework?framework=portable-net45%2Bnetcore45%2Bwpa81%2Bwp8 which detects the 259 profile.

To be honest I'm not a complete expert on this so we might need a nuget expert to clarify. But IMHO one should only use one of the officially supported profiles (because otherwise nuget/msbuild are selecting the next best matching profile anyway if I understood that correctly). Therefore we print the warning at the moment.

Sadly there is currently nothing you can do as a user to get rid of this warning besides not using this package and besides reporting this to the package authors...

**Comment by simonalexandergilbert** [comment]
I've run into the same problem. Are we any closer to a fix?

**Comment by forki** [comment]
Is it an official target?

**Comment by simonalexandergilbert** [comment]
Not quite sure what you mean by that. I'm running Paket version 5.7.2 on Appveyor, and each build seems to just hang after hitting this point - 

```
The profile 'portable-net45+win8+wp8+wp81+wpa81' is not a known profile. Please tell the package author.
Could not detect any platforms from 'xamarintvos10'
Could not detect any platforms from 'xamarinwatchos10'
The profile 'portable-net45+win8+wp8+wp81+wpa81' is not a known profile. Please tell the package author.
```

**Comment by matthid** [comment]
@simonalexandergilbert This issue is about the warning, a "hang" is definitely a different issue... Please open a new issue with a verbose log for the hang...

**Comment by simonalexandergilbert** [comment]
Ok, thank you.

**Comment by haf** [comment]
How do I know what package paket is warning about? The warning comes at the end of resolving all packages?

**Comment by forki** [comment]
We're working on a solution

Am 15.08.2017 15:18 schrieb "Henrik Feldt" <notifications@github.com>:

**Comment by matthid** [comment]
This should be fixed as soon as https://github.com/fsprojects/Paket/pull/2632 is merged.
With "fixed" we mean paket will tell you which package is to blame.
