### ISSUE TITLE
Paket releases too often and often too soon. hard to find docs about locking the paket version

### ISSUE THREAD

**Issue by ramondeklein** [fsprojects/Paket#2517]
### Description
Paket is a great way to deal with packages and versioning, but the versioning of Paket itself is not on a level suitable for enterprise development. New versions a released several times a day. We cannot keep up and we don't know which versions are stable.

### Repro steps
Run `paket.bootstrapper.exe` and find out that an updated version is downloaded each time ;-)

### Expected behavior
Paket should provide a stable release that is tested and will be maintained with bugfixes only. For the more experimental features an alpha/beta branch should be provided to test new features.

### Actual behavior
Our GIT repository is filled with changes to C# project files, because Paket changes the behavior several times. Some versions keep downloading a lot of versions, spit out a lot of warnings, ...

### Known workarounds
Keep with the version you like, but it's hard to coordinate this within your team.

**Comment by matthid** [comment]
@ramondeklein While I agree in theory and have thought about this myself. It is a little more difficult in practice than you might think. This is because of several reasons:

 - We depend on people to provide tests for bugfixes/new features for regressions to minimize. I think we can do better here and more often don't accept PRs as fast as we do now and request more tests. But often writing tests is hard, especially when fixing/reworking stuff for 3rt party nuget server implementations (as we are doing at the moment). We are interested in good ways to handle this and PRs ;). See https://github.com/fsprojects/Paket/issues/2511. Often we are forced to provide fixes for a broken state and don't add the necessary regression tests afterwards (again PRs are welcome to help out).
 - Practice and download numbers shows that prereleases are just not downloaded and tested at the rate we wish. Therefore even when we know that a change might be risky we have no other choice than releasing it because it doesn't really matter if it breaks now and we revert or we do the same after alpha phase.
 - Often after alpha phases it makes bugs more difficult to identify the faulty commit. This is much more easy in the current process.

So yes I get your point. And yes we tried that. Not working very well.

Finally it's obvious: This is an open-source project. The best way to make it stable for your use-case and stuff we broke for you in recent time is to provide test-cases for them. CI will make sure they won't break again.

**Comment by lexarchik** [comment]
You can use paket.bootstrapper in magic mode, fix version of paket in paket.dependencies file and update it only when you want (when you see new functions or bugfixes that will be useful for your project)

**Comment by forki** [comment]
https://fsprojects.github.io/Paket/dependencies-file.html#Required-Paket-version

^^ this allows you to require a specific version from the deps file. this allows you to stay stable as long as you want.

Fast releases are really really important for us - other wise we can't react to that things in netcore and nuget ecosystem.

**Comment by matthid** [comment]
I think it's worth discussing the underlying issue. I think this is not about a lot of releases, but about stability.

It's not like we don't want to improve stability. It's just that we try this particular suggestion from time to time, and from experience it makes things worse for us, because we actually release more untested stuff in a single time (because nobody uses prereleases).

We are open for suggestions and definitely would love to get help on this. Additionally It's always a good idea to lock versions as @forki suggests, because you need stable version numbers for stable builds (that's why we have lockfiles after all).

**Comment by forki** [comment]
Regarding changes in csproj files: with the new MSBuild we don't change the csproj at all. So when you convert to this model the csproj will stay stable for very very long time,

**Comment by lexarchik** [comment]
btw, maybe [quick start](https://fsprojects.github.io/Paket/getting-started.html) should say something about locking paket version in deps file (or at least describe that renamed paket.bootstrapper would download newest paket version every time)?

**Comment by forki** [comment]
yes please send a PR to the docs that clarifies things. would be very welcomed
