### ISSUE TITLE
Projects Include AutoGenerateBindingRedirects

### ISSUE THREAD

**Issue by BlythMeister** [fsprojects/Paket#2573]
### Description

When paket is generating assembly binding re-directs it should state AutoGenerateBindingRedirects = true in the project file.

Without this, MSBuild will try and unify the references and will create MSB3277 warnings that there is a conflict.
We know there is a conflict, this is why paket added the redirect ;)

### Repro steps

Create project which needs a binding redirect (ensure AutoGenerateBindingRedirects is not in proj file).
Get paket to add the redirect
AutoGenerateBindingRedirects is not added to the project

### Expected behavior

AutoGenerateBindingRedirects is added with value of true

### Known workarounds

Manually add AutoGenerateBindingRedirects.

**Comment by BlythMeister** [comment]
NB: Or some other way to prevent MSBuild from attempting assembly unification...

**Comment by forki** [comment]
Mhm didn't know that. Would love to see a pr then

Am 31.07.2017 4:28 nachm. schrieb "Chris Blyth" <notifications@github.com>:

**Comment by BlythMeister** [comment]
@forki the docs on what that property does are pretty sketchy...i added it to some things i had that warning on, and the warning went away....but not sure if it's right to add it to everything...

**Comment by BlythMeister** [comment]
This has got me again!
In referenced issue it was suggested to always add it.

I'll investigate how possible that is.

**Comment by 0x53A** [comment]
As far as I know, MSBuild also checks the app.config and only complains if there is no existing redirect.

Until now I've always tried to use forced redirects from paket, because then I can copy-paste an app.config file from source control to prod. Otherwise I'd need to make sure to insert the redirects block back first.

https://github.com/fsprojects/Paket/blob/3bfe0a1073e0ca78a2c31550948ec0a6d53af462/src/Paket.Core/Installation/BindingRedirects.fs#L170-L172

There is a check for ``true``, should there also be a check for ``force``?
