### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by vik-borisov** [fsprojects/Paket#2603]
Hey.
I update the packages and get such statistics. Is this ok or not?

![image](https://user-images.githubusercontent.com/4207463/29205887-930afb32-7ea9-11e7-96ef-8e9075fee538.png)

paket.dependecies

> source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json
> source https://dotnet.myget.org/F/cli-deps/api/v3/index.json
> source https://api.nuget.org/v3/index.json
> framework = netcoreapp1.1
> 
> nuget Dapplo.Jira
> nuget Dapplo.Bitbucket
> nuget Dapplo.Log ~> 1
> nuget FluentScheduler
> nuget Microsoft.Extensions.Caching.Memory
> nuget FSharp.Control.FusionTasks.FS40.netcore > 1 prerelease
> nuget FSharp.Core 
> nuget Telegram.Bot >= 11.1.0 prerelease
> nuget FSharp.NET.Sdk >= 1.0.0
> nuget System.Security.Cryptography.Algorithms
>

**Comment by forki** [comment]
Can you please try to reorder the sources. Move the myget stuff down so
that only things that are actually on myget are below the myget source..

Like

Source nuget...
nuget package1

Source myget
nuget package2
nuget package3

The rule is that we only check sources that are above the current line. So
for that example package1 is only checked in nuget.org

package2 will be checked in MyGet and nuget.

Am 11.08.2017 10:30 schrieb "Viktor Borisov" <notifications@github.com>:

**Comment by vik-borisov** [comment]
@forki thx for the answer.
I deleted the lines
> Source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json
> Source https://dotnet.myget.org/F/cli-deps/api/v3/index.json

And now performance:
![image](https://user-images.githubusercontent.com/4207463/29206777-9d9e70a2-7ead-11e7-9f9a-0fe23e601e0f.png)

Is it because there were many sources? Or there are some problems with MyGet?

**Comment by matthid** [comment]
Imho the suggestion of @forki is only a workaround for now.
I'd blame all the fallbacks because we do them even when we retrieve empty results... (empty results can be a valid result and often times they are on 3rd party servers, but we don't trust them for some reason).

I hope this can be fixed by https://github.com/fsprojects/Paket/pull/2582 
Stuff is moving to fast and too many changes and different servers are coming in, so sadly I can barely keep up. Instead of all those "quick"-fixes I'd rather get some tests that check correctness.

Currently we are in a workflow which breaks and repairs back and forth and we will never get into a performant and correct state (sadly)

**Comment by forki** [comment]
@matthid I'm less pessimistic about it. We will sort it out. ;-)

Am 11.08.2017 10:59 vorm. schrieb "Matthias Dittrich" <
notifications@github.com>:

**Comment by vik-borisov** [comment]
I combined all the sources into one and the speed increased 9 times. However, in Myget all proxy sources are marked as unlisted.
Can the Paket to search in unlisted packages?

**Comment by matthid** [comment]
@vik-borisov Can you please retry with  5.86.0-alpha002. Otherwise we might break you on next release.

**Comment by vik-borisov** [comment]
@matthid Everything is fine, thank you for your concern
