### ISSUE TITLE
Please use the new syntax: '--references-files' has been replaced by '--references-file'.

### ISSUE THREAD

**Issue by lukasz-pyrzyk** [fsprojects/Paket#2646]
### Description
`paket.targets` uses od syntax: `--references-files`, which causes an additional log information:

> Please use the new syntax: '--references-files' has been replaced by '--references-file'.

### Expected behavior
`paket.targets` should use new syntax

### Actual behavior
Old syntax is used, which causes a log message

I will be happy to submit a PR if you agree

**Comment by forki** [comment]
Cc @agross
The problem is that this parameter takes multiple values comma separated. I
think plural would be correct.

Am 22.08.2017 9:52 vorm. schrieb "Łukasz Pyrzyk" <notifications@github.com>:

**Comment by agross** [comment]
The new syntax reports the following: `restore packages from a paket.references file; may be repeated`

So instead of `paket restore --references-files file1,file2,file3` which is a PITA w.r.t. completing `**/*paket.references` file names on the command line you would `paket restore --references-file file1 --references-file file2 --references-file file3`.

**Comment by forki** [comment]
Ok I actually agree. Just someone needs to do the MSBuild magic here

Am 23.08.2017 6:19 nachm. schrieb "Alexander Groß" <notifications@github.com

**Comment by matthid** [comment]
Yes please send PR :)
