### ISSUE TITLE
github dependencies should support Github Enterprise not just github.com

### ISSUE THREAD

**Issue by tebeco** [fsprojects/Paket#2669]
### Description

We tried to use 
https://fsprojects.github.io/Paket/github-dependencies.html
but it seems to be hardcoded to https://github.com/
At work we have like 100 repo hosted un a `Github Enterprise` 

for example we host our Fake.fsx build that is 99% the same for each app we build
but we have to duplicate it per application, ending up in tons of issues since it's hard to track changes of a copy / past

### Repro steps

Hard ;) Setup a github Enterprise and try to use paket over internal repo

### Expected behavior

Beeing able to add `named sources` for `github` and `github entreprise`
default should point github.com
The hard part is when you need both `github.com` and `github.company.com`
It would require a `token` (like a Name), so you could do in the `paket.dependency` :
`GITHUB xxx` <== github.com
`GITHUB TOKEN xxx` or use : `GITHUB xxx id:TOKEN` 

### Known workarounds

using `URL` + RAW for github works but the file location did not feel right at all so we rolledback to copy/paste

**Comment by forki** [comment]
Github deps are github.com deps that's right.
What about using git deps instead?

Am 26.08.2017 3:32 nachm. schrieb "TeBeCo" <notifications@github.com>:

Description

We tried to use
https://fsprojects.github.io/Paket/github-dependencies.html
but it seems to be hardcoded to https://github.com/
At work we have like 100 repo hosted un a Github Enterprise

for example we host our Fake.fsx build that is 99% the same for each app we
build
but we have to duplicate it per application, ending up in tons of issues
since it's hard to track changes of a copy / past
Repro steps

Hard ;) Setup a github Enterprise and try to use paket over internal repo
Expected behavior

Beeing able to add named sources for github and github entreprise
default should point github.com
The hard part is when you need both github.com and github.company.com
It would require a token (like a Name), so you could do in the
paket.dependency :
GITHUB xxx <== github.com
GITHUB TOKEN xxx or use : GITHUB xxx id:TOKEN
Known workarounds

using URL + RAW for github works but the file location did not feel right
at all so we rolledback to copy/paste

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/fsprojects/Paket/issues/2669>, or mute the thread

**Comment by tebeco** [comment]
will try Monday ^^ i did not think using url with GIT package

**Comment by matthid** [comment]
> using URL + RAW for github works but the file location did not feel right at all so we rolledback to copy/paste

Cam you elaborate this a bit?

**Comment by tebeco** [comment]
is it possible to change the fullpath to download ?

the example i took is the build.fsx the makes sense when you build, either if we have a build folder or more often in the same directory as the paket.dependencies (root level)

other example are sharing csharp file across repository (we wanted to avoid creating of a nuget like 3-4 simple POCO)

i'm in holiday so i don't have access to my workstation or any computer (just a phone^^ 
) to get into more details
