### ISSUE TITLE
parse error in framework restrictions

### ISSUE THREAD

**Issue by forki** [fsprojects/Paket#2803]
deps file with:

    source https://www.nuget.org/api/v2
    framework: netstandard 2.0

leads to lock file with:

    RESTRICTION: == net2

which is clearly wrong. The parser should throw an error instead.

Correct would be:

    source https://www.nuget.org/api/v2
    framework: netstandard2

**Comment by csmager** [comment]
I've had a quick look at this. Is it documented anywhere what syntax is expected to work here? The [docs I found](https://fsprojects.github.io/Paket/dependencies-file.html) only seem to imply comma delimited frameworks, but I'm pretty sure it's more than that.

[This seems to be the relevant code](https://github.com/fsprojects/Paket/blob/9bda1704f3bed849e3e28d9f313de7b7e5ad0090/src/Paket.Core/Versioning/Requirements.fs#L558-L606), and my inference from that is the following expressions are intended to be supported and that expressions can be comma delimited:

| Value | Result |
| --- | --- |
| net45 | Exactly net45 |
| = net45 | Exactly net45 |
| >= net45 | At least net45 |
| >= net45 <= net46 | Between net45 and net46 |

Essentially the problem is that none of the operators are really validated, The expression is split on spaces and, in this case, the first token is assumed to be `=`  and `2.0` is parsed as `net2`.

I'd normally write parsers like this using [FParsec](http://www.quanttec.com/fparsec/). Is there a preference to write parsers in the style here / below in `parseRestrictions`?

**Comment by matthid** [comment]
@csmager What you write is correct. The problem is that that the semantics of `>=` and especially `<=` are hard to understand and most of the times confused users. Therefore, I actually removed them from the docs. The problem is that you mentally need to separate frameworks you target, frameworks your references target and framework groups in the dependencies. People seem to confuse those things on a regular basis so keeping it simple and make people list the frameworks they compile for (= target) seems reasonable.

I think the syntax in your table is actually complete. We might consider to fail when the operator is not recognized (the situation here).

We probably wouldn't mind adding FParsec to the dependencies, though it probably is a bit overkill for this bugfix?

**Comment by forki** [comment]
Fparsec was mentioned multiple times. I'm not against it, but I think then
it should be an effort to replace all parsing for v6. I don't think it's a
good idea to do it for minor bug fixes.

Am 30.09.2017 10:58 schrieb "Matthias Dittrich" <notifications@github.com>:

**Comment by matthid** [comment]
@forki Yes exactly that

**Comment by csmager** [comment]
Thanks both - I would agree it would be overkill to add FParsec just for this bug fix (especially given the grammar is so small), but it may be generally a more robust solution for parsing in this & other areas in future. 

I'll take a look at this in the next few days with a view to handling only the expressions listed in the table above & throwing errors if not.

**Comment by forki** [comment]
Cool. Welcome aboard.

Am 30.09.2017 11:10 schrieb "Charles Mager" <notifications@github.com>:

Thanks both - I would agree it would be overkill to add FParsec just for
this bug fix (especially given the grammar is so small), but it may be
generally a more robust solution for parsing in this & other areas in
future.

I'll take a look at this in the next few days with a view to handling only
the expressions listed in the table above & throwing errors if not.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/fsprojects/Paket/issues/2803#issuecomment-333295628>,
or mute the thread

**Comment by csmager** [comment]
Couple more questions. I've implemented stricter parsing per the table above, but I have some failing existing tests. I need some input as to whether the tests are wrong or the table is incorrect or complete:

This test doesn't assert on the parsed framework, but it looks invalid to me - shouldn't the frameworks be comma delimited?
https://github.com/fsprojects/Paket/blob/8a7070f055c2366bd138b2c0d0dbcdeb9c57277c/tests/Paket.Tests/DependenciesFile/ParserSpecs.fs#L224-L239

And this test related to the lock file, but uses the same parsing. Here we have `LinqBridge (>= 1.3.0) - >= net20 < net35`. I would expect this to be `>= net20 <= net35` (and, as a result, the test now fails).

https://github.com/fsprojects/Paket/blob/8a7070f055c2366bd138b2c0d0dbcdeb9c57277c/tests/Paket.Tests/Lockfile/ParserSpecs.fs#L282-L339

**Comment by matthid** [comment]
First, thanks for taking a look into this area...

These are the kind of expected quirks:
 - If we wrote `>= net20 < net35` into the lockfile in previous versions we probably should keep recognizing that. I'm not even sure as what is was read in previous versions. We can warn but probably should not fail
 - "shouldn't the frameworks be comma delimited?" Yes, again I'm not sure how we parsed that in previous versions. Here a parse error might be acceptable, even if previous versions did correctly parse this as `|| (net40) (net35)` which would be the only valid result IMHO.

Maybe @forki can tell us about the potential impact in the ecosystem. I don't see any of the two things widely used.

**Comment by csmager** [comment]
Re the lockfile, the test happens to assert on the LinqBridge framework restriction. This is expected to be
```
(FrameworkRestriction.Between(FrameworkIdentifier.DotNetFramework(FrameworkVersion.V2),FrameworkIdentifier.DotNetFramework(FrameworkVersion.V3_5))
```
which is the same as we'd parse for `>= net20 <= net35`. I'll amend so we accept `<` as well as `<=`.

Re `net35 net40`, I would expect this to return `net40` currently (for the same reason we return `net2` for `netstandard 2.0` - net35 will be assumed to be `=`). I'd suggest I amend the test to insert the missing comma and prevent the parsing error and continue to raise an error for this.

**Comment by matthid** [comment]
> which is the same as we'd parse for >= net20 <= net35

Then a warning is definitely acceptable (as it is suspicious that `<=` is the same as `<`).

> I would expect this to return net40

Yes then parsing error is fine.

> I'd suggest I amend the test to insert the missing comma and prevent the parsing error and continue to raise an error for this.

Yes that or use it as negative test, whatever feels more useful.
