### ISSUE TITLE
Queries to NuGet sources should respect case-sensitivity

### ISSUE THREAD

**Issue by viktor-svub** [fsprojects/Paket#2847]
### Description

Paket 5.114.4 queries sources with package name lower-cased, resulting in lookup failure. 
Package sources can be case-sensitive, and Paket should respect `paket.dependencies` case. 

### Repro steps

1. Upload you camel-case named package (like "My.Secret.Package.SDK") to case-sensitive source, e.g. Artifactory NuGet repository. 
2. Create `paket.dependencies` with your package name, may be direct and transitive at the same time, with constraint like `My.Secret.Package.SDK ~> 1.2.3.4`. 
3. Call `paket update --no-install --force` to create `paket.lock`.

### Expected behavior

Queries to any sources shall respect the package name casing, either from `paket.dependencies` or as downloaded (e.g. from nuspec file/package metadata). 
If there are multiple case versions detected for a package, warning or error should be produced, and in case of choosing a warning, sources should be queried for all the known alternatives. 

### Actual behavior

Observe the queries generated from STR: they will look like: 
  http://nuget.local/artifactory/api/nuget/nugets/Packages(Id='my.secret.package.sdk',Version='1.2.3.4') 
  and return 404 NotFound. 
And Paket will fail with `Conflict detected:
- Dependencies file requested package My.Secret.Package.SDK: == 1.2.3.4
- Available versions:
- (2.3.4.5, [http://nuget.local/artifactory/api/nuget/nugets])
- (1.2.3.4, [http://nuget.local/artifactory/api/nuget/nugets])
- (1.2.3.1, [http://nuget.local/artifactory/api/nuget/nugets])`.

### Known workarounds

None, `paket.dependencies` and the package metadata already match the actual package file/name case, and our NuGet repository, Artifactory, is configured as case-sensitive outside of our control.

**Comment by forki** [comment]
@matthid  we did that right? is there a fallback broken?

**Comment by forki** [comment]
can someone provide an Artifactory repo?

**Comment by viktor-svub** [comment]
I don't have any external hosting available; there is https://www.jfrog.com/artifactory/free-trial/ is you have environment for repro. 
As far as I see though, this calls for a whitebox fix -- is there a path where we use the package names lower-cased? Should there be one? It should not be specific to Artifactory.

**Comment by forki** [comment]
nuget package names are case-insensitive. that is an artifactory bug. but we need to work around it

**Comment by vbfox** [comment]
So this issue (or a very similar one) broke things for us, with paket having very weird behaviors since a few weeks ago (When we upgraded to a version with the lowercasing). Some changes to dependencies worked in `paket install` but others produced infinite loops.

From a fiddler trace it seemed that Paket was trying to get the problematic package from our ProGet with the lowercase syntax and never trying the non-lowercase one.

Turns out it was a produced by the fact that one of our package source is a TeamCity feed cached by ProGet (`Paket -> ProGet -> TeamCity)` :
* TeamCity feed is case-sensitive on nuget Id (I created a new issue on that https://youtrack.jetbrains.com/issue/TW-52167 they had an old one that they closed, let's hope this one will change their mind)
* ProGet forward requests as-is by default on "connected feeds" except if a package version has been downloaded from it's UI, then it's considered local. Local package are handled by ProGet internal search that is case insensitive. So we ended up with some versions downloadable and other not.
* I suspect that paket wasn't trying a non-lowercased URL a for some versions of the same package or diff the lowerased version works.
* Paket resolver when faced with this case (I didn't reduce from our full dependencies so I don't have a repro) entered an infinite loop...

On our side I solved this by going back to paket `5.85.0` and I'll look into removing TeamCity from the equation.

But I suspect that TeamCity & Artifactory won't be the only ones having that problem. They obviously need to be fixed but in the mean time paket lowercasing PackageId is creating problems with the existing servers.

If the official client is sending IDs as-is in this case (I didn't test if they hit this exact URL) maybe doing the same is the most-compatible solution ?

**Comment by forki** [comment]
Is there a way to reproduce this?

Am 31.10.2017 14:41 schrieb "Julien Roncaglia" <notifications@github.com>:

**Comment by vbfox** [comment]
I'll try to but won't be very simple I suspect that it'll finish with 1 TC docker and 1 ProGet docker

**Comment by vbfox** [comment]
Also contacting TeamCity it seem that the latest version solved it (2017.1) so we can keep using latest paket.  And it's one more server that is correctly behaving regarding IDs 🙌

**Comment by forki** [comment]
Ok still we need to work around it. If I just had an repro....

Am 02.11.2017 10:01 schrieb "Julien Roncaglia" <notifications@github.com>:

**Comment by Dirk-Kuypers** [comment]
Just for completeness, this is known since years to JFrog. :-(
https://www.jfrog.com/jira/browse/RTFACT-6112
I will try to point our central IT guys at it but we have bought not enough licenses to be a big player for JFrog.

**Comment by casz** [comment]
Could add a flag `--preserve-casing` to alleviate the problem?

**Comment by forki** [comment]
Actually it's not really about the flag. It's more that we need to figure
out which calls are going wrong right now

Am 12.12.2017 16:19 schrieb "Joseph Petersen" <notifications@github.com>:

**Comment by SimonasMatenas** [comment]
Hey, I am new to paket. I migrated our project to paket to see that paket is not consistent. We are using JFrog artifactory. I will provide two examples of paket restore. From fiddler logs.
1) This failed with conflict.

> 192	404	HTTPS	artifactory.core.rcsops.com	/artifactory/api/nuget/xstream-nuget-virtual/Packages(Id='xstream.coordination',Version='1.0.87')
> 201	404	HTTPS	artifactory.core.rcsops.com	/artifactory/api/nuget/xstream-nuget-virtual/Packages(Id='xstream.coordination',Version='1.0.87')
> 208	404	HTTPS	artifactory.core.rcsops.com	/artifactory/api/nuget/xstream-nuget-virtual/Packages(Id='xstream.coordination',Version='1.0.87')
> 219	404	HTTPS	artifactory.core.rcsops.com	/artifactory/api/nuget/xstream-nuget-virtual/Packages(Id='xstream.coordination',Version='1.0.87')
> 227	404	HTTPS	artifactory.core.rcsops.com	/artifactory/api/nuget/xstream-nuget-virtual/Packages(Id='xstream.coordination',Version='1.0.87')
> 235	404	HTTPS	artifactory.core.rcsops.com	/artifactory/api/nuget/xstream-nuget-virtual/Packages(Id='xstream.coordination',Version='1.0.87')

From this example we can see paket did not tried to use upper case for package. I ran same command again, clearing paket cache before doing restore.

2) Succeeded.
> 7	404	HTTPS	artifactory.core.rcsops.com	/artifactory/api/nuget/xstream-nuget-virtual/Packages(Id='xstream.coordination',Version='1.0.87')
> 13	404	HTTPS	artifactory.core.rcsops.com	/artifactory/api/nuget/xstream-nuget-virtual/Packages(Id='xstream.coordination',Version='1.0.87')
> 20	200	HTTPS	artifactory.core.rcsops.com	/artifactory/api/nuget/xstream-nuget-virtual/Packages(Id='xStream.Coordination',Version='1.0.87')
> 23	200	HTTPS	artifactory.core.rcsops.com	/artifactory/api/nuget/xstream-nuget-virtual/Download/xStream.Coordination/1.0.87

As you can see paket running exact same command succeeded this time. On 3rd try it got correct casing and downloaded package with 4th request.

Paket version 5.129.0
