### ISSUE TITLE
[Discussion] Best way for paket to support multi-targeting in new project structure?

### ISSUE THREAD

**Issue by eiriktsarpalis** [fsprojects/Paket#2947]
I've been spending the holidays porting some of my libraries to netstandard2.0, and it's mostly been working great for me. However, I must say that I find the duplication of project files to be taxing, especially for large-ish solutions. This is why I found [this article on multi-targeting projects](https://weblog.west-wind.com/posts/2017/Jun/22/MultiTargeting-and-Porting-a-NET-Library-to-NET-Core-20) particularly promising. 

I'd be interested to know if there's a way for paket to support this structure, but it seems pretty much antithetical to the design philosophy `paket.references` (e.g. you can't reference two different versions of FSharp.Core based on framework constraints). I was wondering if there are any plans to incorporate support for this.

**Comment by forki** [comment]
Duplication of project files? Paket supports multi-target in new project
system already

Am 27.12.2017 13:43 schrieb "Eirik Tsarpalis" <notifications@github.com>:

I've been spending the holidays porting some of my libraries to
netstandard2.0, and it's mostly been working great for me. However, I must
say that I find the duplication of project files to be taxing, especially
for large-ish solutions. This is why I found this article on
multi-targeting projects
<https://weblog.west-wind.com/posts/2017/Jun/22/MultiTargeting-and-Porting-a-NET-Library-to-NET-Core-20>
particularly promising.

I'd be interested to know if there's a way for paket to support this
structure, but it seems pretty much antithetical to the design philosophy
paket.references (e.g. you can't reference two different versions of
FSharp.Core based on framework constraints). I was wondering if there are
any plans to incorporate support for this.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/fsprojects/Paket/issues/2947>, or mute the thread

**Comment by eiriktsarpalis** [comment]
It doesn't seem to be working for me. Could you point me to projects/documentation that does this? It looks like paket itself is using the old project format. Other already ported OSS projects I checked (FsCheck & Unquote) are using the dual project approach.

**Comment by matthid** [comment]
>e.g. you can't reference two different versions of FSharp.Core based on framework constraints

No, the only paket feature to allow that are "groups". But I'm not sure if they are properly supported in new new project files already. Usually we still try to convince people that depending on different versions is not a good idea.

**Comment by eiriktsarpalis** [comment]
>  Usually we still try to convince people that depending on different versions is not a good idea.
I think in the case of FSharp.Core it makes sense to have different versions per target. I highly dislike forcing 4.2 for net45 consumers of a library like Argu. It's been written against 3.1, so it should be supporting 3.1.

**Comment by forki** [comment]
There is no documentation for paket around it since it should work like
standard. Can you upload a repro where paket thinks it is old format?

Am 27.12.2017 15:27 schrieb "Eirik Tsarpalis" <notifications@github.com>:

**Comment by eiriktsarpalis** [comment]
Here you go https://github.com/fsprojects/Argu/tree/ec72521eda9e0adc6577b313c7a1de38041f6893/src/Argu.Core

**Comment by forki** [comment]
But paket did not install any lib references, so it's not thinking it is
old project system. Right?

Am 27.12.2017 17:02 schrieb "Eirik Tsarpalis" <notifications@github.com>:

**Comment by eiriktsarpalis** [comment]
I don't follow, shouldn't it be installing references? It works in master where it's single target.

**Comment by forki** [comment]
No in new project format the fsproj is freed of that garbage. All happening in memory. Huge benefits.

**Comment by eiriktsarpalis** [comment]
Via `Paket.Restore.targets` I presume. It's failing to restore anything in a multi-target setting though:
<img width="257" alt="capture" src="https://user-images.githubusercontent.com/2813363/34386745-167c59b8-eb22-11e7-8cfa-3a0bd0a064e8.PNG">. Works fine in single-target configuration though.

**Comment by forki** [comment]
That is vs. It doesn't work in VS, but that's unrelated to paket. AFAIK
that is similar issues with nuget

Am 27.12.2017 17:23 schrieb "Eirik Tsarpalis" <notifications@github.com>:

**Comment by eiriktsarpalis** [comment]
It fails to build regardless of VS, e.g. https://travis-ci.org/fsprojects/Argu/builds/322229405

**Comment by forki** [comment]
Anyway we are not doing anything special. If you create a small repro we
can try to find out the cause. But multi targeting used to work, so there
must be some edge case.

Am 27.12.2017 17:29 schrieb "Eirik Tsarpalis" <notifications@github.com>:

**Comment by eiriktsarpalis** [comment]
I created this https://github.com/eiriktsarpalis/Repro. The build failure here however seems to be due to msbuild, not paket (it's failing to build net45 due to it not seeing `ConfigurationManager`).

Anyway, I'd be interested in seeing a paket solution that uses multi-targeting in an approved manner. Could you point me to one, if it exists?

**Comment by forki** [comment]
It's mostly closed source AFAIK (we have some internal stuff).

Am 27.12.2017 18:24 schrieb "Eirik Tsarpalis" <notifications@github.com>:

I created this https://github.com/eiriktsarpalis/Repro. The build failure
here however seems to be due to msbuild, not paket (it's failing to build
net45 due to it not seeing ConfigurationManager).

Anyway, I'd be interested in seeing a paket solution that uses
multi-targeting in an approved manner. Could you point me to one, if it
exists?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/fsprojects/Paket/issues/2947#issuecomment-354146524>,
or mute the thread

**Comment by eiriktsarpalis** [comment]
The build was failing due to an unrelated issue with the project structure 🤦‍♂️   . Closing this for now. I'm still looking for a way to reference different versions of FSharp.Core per target, will come back with a concrete proposal later.
