### ISSUE TITLE
Fleece should not include LinqBridge for a .NET 4.5 project

### ISSUE THREAD

**Issue by ctaggart** [fsprojects/Paket#307]
When installing `Fleece` in a `.NET 4.5` project, `LinqBridge` should not show up as dependency. This is related to #140. //cc @mausch

The test project to reproduce is here:
https://github.com/ctaggart/Paket09x/commits/master

![image](https://cloud.githubusercontent.com/assets/80104/4815865/9cab78d4-5eda-11e4-882b-297e921bd2ba.png)

https://www.nuget.org/packages/ReadOnlyCollectionExtensions/

![image](https://cloud.githubusercontent.com/assets/80104/4815884/be416ef4-5eda-11e4-8161-35fc4f5e34a9.png)

With it added as a dependency, you get warnings like this:

![image](https://cloud.githubusercontent.com/assets/80104/4815948/3858e834-5edb-11e4-970f-c53777a29595.png)

because it includes implementations of `System.Action` and `System.Func`

![image](https://cloud.githubusercontent.com/assets/80104/4815976/6dc8a57c-5edb-11e4-8e8b-b08feb2f36a6.png)

**Comment by mausch** [comment]
I'm just getting started with Paket and having this problem in version 0.25.1.0. The problematic package for me is https://www.nuget.org/packages/Cassette/ , it's choking on the Iesi.Collections dependency even though it's a .NET 4.5 project.

I only ran `paket convert-from-nuget`, then fixed a couple minor issues with incorrectly named packages, then `paket install`, do I need to do anything else?

@ctaggart have you opened another issue about this? I can't seem to find it.

**Comment by forki** [comment]
What's the concrete error?
What's your dependencies file?

**Comment by mausch** [comment]
The exact error is (when running `paket install`):

```
  Can't resolve:
    - Iesi.Collections <  4.0
       - from Cassette 2.4.2
 Please try to relax some conditions.
```

This project has a huge list of dependencies, but the problem seems to be that [NHibernate 4.0.2.4000](https://www.nuget.org/packages/NHibernate/4.0.2.4000) requires Iesi.Collections (≥ 4.0 && < 5.0) and this conflicts with Cassette's requirement of Iesi.Collections (< 4.0) (which only applies to .NET 3.5 and therefore should be ignored for this particular project).

Let me know if that's enough or you want a more precise repro.

Cheers

**Comment by forki** [comment]
Mhm. I reopened https://github.com/fsprojects/Paket/issues/322 - this could
help.

The exact error is (when running paket install):

  Can't resolve:
    - Iesi.Collections <  4.0
       - from Cassette 2.4.2
 Please try to relax some conditions.

This project has a huge list of dependencies, but the problem seems to be
that NHibernate 4.0.2.4000
<https://www.nuget.org/packages/NHibernate/4.0.2.4000> requires
Iesi.Collections (≥ 4.0 && < 5.0) and this conflicts with Cassette's
requirement of Iesi.Collections (< 4.0) (which only applies to .NET 3.5 and
therefore should be ignored for this particular project).

Let me know if that's enough or you want a more precise repro.

Cheers

—
Reply to this email directly or view it on GitHub
<https://github.com/fsprojects/Paket/issues/307#issuecomment-72055504>.

**Comment by forki** [comment]
I now understand the issue. I'll try to come up with a solution.

**Comment by forki** [comment]
as a workaround add 

    nuget Iesi.Collections == 4.0.1.4000

to your dependencies file. This will force the version.

**Comment by mausch** [comment]
Thanks, that workaround did the trick. I just have to be careful with `paket simplify` until this is fixed, as it removes that versioning constraint from the dependencies file (or is that a separate issue?)

**Comment by forki** [comment]
Yes. I'm working on a better solution. Internally we already have
everything to say: just don't care about net35. But this is not part of the
dependencies file yet
