### ISSUE TITLE
Framework restriction violated in paket.dependencies for System.Collections.Immutable

### ISSUE THREAD

**Issue by ruhullahshah** [fsprojects/Paket#3143]
### Description

Setting `framework` to `auto-detect` or `net45` still doesn't stop Paket from downloading `NETStandard.Library` for `Systems.Collections.Immutable`

PFA `paket.dependencies` & `paket.lock` files for the same.

### Expected behavior

`packages`  dir. should only contain Systems.Collections.Immutable

### Actual behavior

`packages`  dir. contains `Systems.Collections.Immutable`, `NetStandardLibrary` and its dependencies leading to package pollution.

Paket version: `5.155.0`

[paket-files.zip](https://github.com/fsprojects/Paket/files/1884529/paket-files.zip)

**Comment by ruhullahshah** [comment]
In case this helps, we verified the behavior with Paket-4.8.4 and this version works as expected. This was the previous version we were using.

**Comment by jbaehr** [comment]
The main problem arises when the not-required packages are unavailable (corporate network, internal nuget-server, manual license verification, etc.). With paket-4.8.4 it just worked, but paket-5 fails because packages that no one needs are not available. And we're talking about a lot of packages; in the minimal example vanilla nuget downloads 2.7MB vs. 273MB that paket downloads.

Before we can think about crafting a PR we must understand the underlaying problem. Why does paket follows the `netstandard` dependencies when the target framework is .NET-4.5? I must confess that I do not fully understand your explanation above regarding the portable profile that nuget seems to prefer...

**Comment by matthid** [comment]
Usually, paket will just follow all dependencies constrained by the dependency groups, but you already are constraining via `framework net45`.
This means paket only needs to follow the one dependency group that fits "best" to `net45`.
In `Systems.Collections.Immutable` there are:
 - `netcoreapp2.0`
 - `netstandard1.0`
 - `netstandard2.0`
 - `portable-net45+win8+wp8+wpa81` (Shown as Portable Class Library (.NETFramework 4.5, Windows 8.0, WindowsPhone 8.0, WindowsPhoneApp 8.1) on https://www.nuget.org/packages/System.Collections.Immutable/1.5.0-preview1-26216-02

Paket and NuGet would immediately prefer a full framework moniker because we are on the full framework (even net35) but there is none. From the Paket side of view `netstandard1.0` is the "nearest" framework in this scenario (all packages with `netstandard1.0` are compatible and run on `net45` according to https://docs.microsoft.com/en-us/dotnet/standard/net-standard). This is because we internally prefer `netstandard` over portable profiles in those scenarios. This is because portable profiles are obsolete at this point.

NuGet for some reason prefers `portable-net45+win8+wp8+wpa81` but I'm not sure if this is some quirk or what the rationale behind that is. Probably because of compatibility.

Does this clear up the confusion?

Regarding the number of packages: This is basically a temporary problem because of `netstandard1.0`. netstandard2.0 improves the situation but is not compatible with net45. So one solution would be to upgrade to a more recent full framework compatible with netstandard2.0. This way only a smaller subset of packages would need to be verified.

Technically everything should work just fine after adding the packages to your feed (at least I don't see a reason right now why it wouldn't)

The easiest solution is probably to stay on 1.3.1 https://www.nuget.org/packages/System.Collections.Immutable/1.3.1 Which should work because it has the full framework moniker with empty dependencies. It is not really that unusual that you have to stay on older package versions if you don't upgrade your framework version.

**Comment by ruhullahshah** [comment]
Thanks for the clarification. We are evaluating alternatives mentioned above.
