### ISSUE TITLE
Please document the assumed development process with Paket

### ISSUE THREAD

**Issue by Bikeman868** [fsprojects/Paket#3299]
### Description

As a newcomer to Paket I am having real problems in understanding who should run what Paket commands at what times.

For example if I start a new solution and set up Paket for it, when other developers check out this source code should they run `paket install` or `paket restore` or something else to get their local copy into a compilable state?

This also applies to our TeamCity continuous integration system. Right now I have several projects that compile and run locally  but either do not compile or do not run correctly when built by TeamCity. I added a TeamCity build step to do `paket restore` but I am not confident that this is the right thing to do.

I think another common scenario is switching branches in Git. The other branch might have different NuGet dependencies but switching branches does not affect the dlls in my bin folder. Which paket command should I use after switching branches to fix the bin folder?

I find the individual Paket commands quite well documented, but i can not find too much on how to use Paket correctly in a development environment.

Thanks.

**Comment by matthid** [comment]
> For example if I start a new solution and set up Paket for it, when other developers check out this source code should they run paket install or paket restore or something else to get their local copy into a compilable state?

`paket restore` because they want the exact dependencies last checked-in (`paket.lock`)

you use `paket install` to apply changes you made to `paket.dependencies` into `paket.lock`

> I added a TeamCity build step to do paket restore but I am not confident that this is the right thing to do.

It is. If they don't compile after restore either you should try again locally after `git clean -xdf` or make sure that `paket-files/paket.restore.cached` is not checked into your source control!

> I think another common scenario is switching branches in Git. The other branch might have different NuGet dependencies but switching branches does not affect the dlls in my bin folder. Which paket command should I use after switching branches to fix the bin folder?

again `paket restore` should make sure you have the exact state from `paket.lock` but it might fail as well if `paket-files/paket.restore.cache` is checked-in.

All in all I'd assume you do things the correct way but you have checked-in `paket-files/paket.restore.cache` which you shouldn't.

**Comment by Bikeman868** [comment]
You are right, unless you specifically add paket-files to your .gitignore file then everything gets very messed up.

I still think this documentation would be useful and I am quite happy to write it.
