### ISSUE TITLE
Running dotnet pack with Paket.Restore.Targets referenced in a new csproj file with msbuild 16 fails.

### ISSUE THREAD

**Issue by wastaz** [fsprojects/Paket#3540]
### Description

Running dotnet pack with Paket.Restore.Targets referenced in a new csproj file with msbuild 16 fails.

```
C:\code\xyz\src\.paket\Paket.Restore.targets(298,15): error MSB4064: The "BuildOutputFolder" parameter is not supported by the "PackTask" task. Verify the parameter exists on the task, and it is a settable public instance property. [C:\code\.....csproj]
C:\code\xyz\src\.paket\Paket.Restore.targets(261,5): error MSB4063: The "PackTask" task could not be initialized with its input parameters.  [C:\code\.....csproj]
```

### Known workarounds

Dont install msbuild 16 on the system (luckily I had not gotten around to installing it on the build servers yet) :D 
I have no idea if it is possible to tell dotnet to use a specific version of msbuild, but I havent figured it out so far...but if that is possible that is probably an option as well.

**Comment by forki** [comment]
Oh no, not again. Why is nuget team breaking us again with exactly the same thing. They know about this. Sigh

**Comment by cdrnet** [comment]
Other workaround that works for me (with VS 2019 and 2.2.202 SDK installed): add a global.json file (`dotnet new globaljson`) and force an older SDK version.

**Comment by forki** [comment]
If someone wants to give it a try:

* look at https://github.com/fsprojects/Paket/blob/master/src/Paket.Core/embedded/Paket.Restore.targets#L260

We already have 3 different ways to call the pack task. This is needed since they did not make it backwards compatible. Above those lines we try to figure out on which MSBuild version we are. So the plan is to find a environment variable that tells us that we are on MSBuild 16 and then create a 4th pack task.

**Comment by cdrnet** [comment]
It seems the breaking change was `BuildOutputFolder` being renamed to `BuildOutputFolders`, as seen in `NuGet.Build.Tasks.Pack.targets` sometime between .Net Core SDK 2.1.505 and 2.1.602:

![image](https://user-images.githubusercontent.com/47147/55681341-e81ddd00-5914-11e9-9880-5e291ab182fb.png)
