### ISSUE TITLE
Wrapped msbuild for .net core project using paket on linux causes System.TypeLoadException

### ISSUE THREAD

**Issue by wallymathieu** [fsprojects/Paket#3547]
### Description

On Ubuntu while building projects using .net core I get:
```
error MSB4018: System.TypeLoadException: Could not load type of field 'Microsoft.NET.Build.Tasks.DependencyContextBuilder:_filteredPackages' (12) due to: Could not resolve type with token 01000027 from typeref (expected class 'NuGet.Packaging.Core.PackageIdentity' in assembly 'NuGet.Packaging, Version=5.0.0.6, Culture=neutral, PublicKeyToken=31bf3856ad364e35') assembly:NuGet.Packaging, Version=5.0.0.6, Culture=neutral, PublicKeyToken=31bf3856ad364e35 type:NuGet.Packaging.Core.PackageIdentity member:(null)
```

see [travis build](https://travis-ci.org/wallymathieu/elastic-studies/builds/516551053?utm_source=github_status&utm_medium=notification)

The environment from travis:
```
0.01s$ mono --version
Mono JIT compiler version 5.18.1.0 (tarball Fri Mar 15 20:45:47 UTC 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(600)
	Suspend:       preemptive
	GC:            sgen (concurrent by default)
1.20s$ msbuild /version
Copyright (C) Microsoft Corporation. All rights reserved.
16.0.0.0
0.26s$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.2.202
 Commit:    8a7ff6789d
Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.202/
```

@A-Manning also experienced the issue on `Ubuntu 18.04.2 x86_64` for .net core 2.2.202

### Repro steps

A non minimal reproduction step would be to build the following project [elastic-studies at specific commit](https://github.com/wallymathieu/elastic-studies/tree/39237fa36439d9a66168314dff1223f89da6a757)

### Expected behavior

The expected behavior would be that paket builds the project (since that can be done with dotnet cli) on linux

### Actual behavior

The wrapped msbuild step in paket fails with `TypeLoadException`.

### Known workarounds

Skip paket and use .net cli directly

**Comment by inosik** [comment]
As I see your build script tries to build the solution file with MSBuild directly:

https://github.com/wallymathieu/elastic-studies/blob/39237fa36439d9a66168314dff1223f89da6a757/build.fsx#L57

Can you try to build the solution with `dotnet build` instead? To me it looks like your build is trying to use MSBuild 15.0 (https://travis-ci.org/wallymathieu/elastic-studies/builds/516551053#L1755), but the .NET SDK 2.2.202 should be MSBuild 16.0.

**Comment by A-Manning** [comment]
@inosik  I get the same error with msbuild 16.0.0.0, mono 5.18.1.3

**Comment by inosik** [comment]
I just tried this on my Mac (Mono 5.18.0.225), and I get the same error if I do `msbuild elastic-studies.sln`. However, if I use `dotnet build elastic-studies.sln`, it builds all the projects in the solution just fine.

The problem is that the build starts with MSBuild 15.0, which then (wrongly) resolves targets from the .NET SDK 2.2.202, which in turn load and try to run assemblies from that SDK. So the solution is to use MSBuild 16.0, which is included in 2.2.202.

One other solution is to use the .NET SDK 2.2.1xx, which can be done with this `global.json`:

``` json
{
  "sdk": {
    "version": "2.2.105"
  }
}
```

Then `msbuild elastic-studies.sln` also works fine. But I don't know which .NET SDK versions are in the CI image, so YMMV.

**Comment by A-Manning** [comment]
This seems like an issue with FAKE, if anything

**Comment by inosik** [comment]
I don't think so. FAKE does what the build script says, execute MSBuild. The problem is the recent release of MSBuild 16.0. If Mono updates their version, this problem should disappear. It will probably come back though, if somebody does `msbuild project.sln` and sets the SDK version to 2.1.5xx or 2.2.1xx, which ship MSBuild 15.0.

I can reproduce this error with the latest SDK (2.2.203) installed, no FAKE or Paket, and these commands:

``` shell
$ dotnet new classlib -n Issue3547 -o .
$ dotnet restore
$ msbuild
```

**Comment by wallymathieu** [comment]
Good to see a small reproduction 😀. Perhaps this issue should be closed then?

**Comment by inosik** [comment]
Yes, this is an issue with the .NET SDK and MSBuild.

**Comment by wallymathieu** [comment]
Hopefully this issue can guide anyone having the same issue

**Comment by tomilchik** [comment]
> I just tried this on my Mac (Mono 5.18.0.225), and I get the same error if I do `msbuild elastic-studies.sln`. However, if I use `dotnet build elastic-studies.sln`, it builds all the projects in the solution just fine.
> 
> The problem is that the build starts with MSBuild 15.0, which then (wrongly) resolves targets from the .NET SDK 2.2.202, which in turn load and try to run assemblies from that SDK. So the solution is to use MSBuild 16.0, which is included in 2.2.202.
> 
> One other solution is to use the .NET SDK 2.2.1xx, which can be done with this `global.json`:
> 

`dotnet build` does solve the problem - thanks!

But I'm not sure about the explanation above. On my Mac - versions: 
SDK 2.2.203
Mono 5.18.1.3
msbuild (comes with Mono): 16.0.42.1932
NuGet (comes with Mono): 4.8.2.5835

Despite msbuild being 16.0, and SDK 2.2.2xx (maybe I should downgrade it to 2.2.1xx?)  - I'm still having this issue when using msbuild.

**Comment by inosik** [comment]
I doubt the MSBuild bundled with Mono is really a 16.0. MSBuild from Mono 5.20.1.19 (installed via Homebrew) reports this:

``` shell
$ msbuild -version
Microsoft (R)-Build-Engine, Version 16.0.42-preview+g804bde742b für Mono
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

16.0.42.19328
```

(Excuse the German text messages)

However, the path where the MSBuild binaries are located is this: 

``` text
/usr/local/Cellar/mono/5.20.1.19/lib/mono/msbuild/15.0/bin/
--------------------------------------------------^^^^
```

[And this](https://stackoverflow.com/a/52888452):

``` shell
$ monodis --assembly /usr/local/Cellar/mono/5.20.1.19/lib/mono/msbuild/15.0/bin/MSBuild.dll | grep Version
Version:       15.1.0.0
```

> NuGet (comes with Mono): 4.8.2.5835

This is probably the issue here. The .NET SDK 2.2.2xx ships NuGet 5.

> maybe I should downgrade it to 2.2.1xx?

Different projects might need different versions of the .NET SDK, so you might (or rather should) have multiple installed on your dev machine. And to be sure `dotnet build/test/whatever` uses the right one, use `global.json`.

**Comment by inosik** [comment]
Looks like this issue is going to bubble up more often in the upcoming weeks/months: NuGet/Home#7956.

**Comment by tomilchik** [comment]
Baby steps...
Following the note above re: Mono.NuGet (4) vs SDK.NuGet (5) I downloaded the NuGet 5 (following these instructions: ([https://docs.microsoft.com/en-us/nuget/install-nuget-client-tools]) , and aliased `nuget` to point to the newly downloaded version.
This fixed `msbuild` issue: I can now run `msbuild My Solution.sln`.
Build from VS-Community is still failing. Investigating further...
