### ISSUE TITLE
Paket Add should call Install, and not Update

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/Paket#3717]
I believe that calling `paket add` currently calls `paket update` after adding the package to the dependencies file. I believe that this behaviour should be replaced with calling `paket install`.

Currently, calling `paket add` currently will cause the lock file to silently update not just the changes caused by adding the new package but update the entire graph.

**Comment by forki** [comment]
I think it does a a "smart update" which basically is install. Do you have
a repro?

Isaac Abraham <notifications@github.com> schrieb am Mo., 11. Nov. 2019,
22:50:

**Comment by isaacabraham** [comment]
I'll double check and create one

**Comment by isaacabraham** [comment]
Repro repo: https://github.com/isaacabraham/paket-add

Steps to reproduce:

1. Clone repo.
2. Note that Newtonsoft.Json is currently at 12.0.1
3. Add any other package (ideally not related to Newtonsoft) using Paket e.g. `paket add FSharp.Data`.
4. Observe that after the add operation, Newtonsoft.Json has now been upgraded as well.

**Comment by forki** [comment]
Thanks for the repro.

This is an interesting case and actually a nice repro for many confusion that we saw in the past. As already discussed on Twitter Paket add is doing an Paket install and not Paket update. So far that's all correct. 

The problem is in the part that tries to detect which package versions should not change. In GetPreferredVersions we analyze lock file and deps file. For packages that are not listed in the deps file we (aka transitive packages) we record the version from the lock file. Tbh I can't remember why we don't do that for direct dependencies. Maybe @matthid knows a related case?

**Comment by matthid** [comment]
Not really. afaik we run the regular resolver but reorder the versions list. I can't think of a reason why we shouldn't do it for direct dependencies as well...
But in the end there might always be ways where unrelated packages are updated, that is probably a reason why we have overlooked previous reports...

**Comment by forki** [comment]
OMG I think I found the bug. WTF!!?

**Comment by forki** [comment]
@isaacabraham please retry with latest

**Comment by isaacabraham** [comment]
@forki cool. Was this actually then something where it did an update rather than install accidentally or something else?

**Comment by forki** [comment]
It did an install without pinning anything. So yes that's basically an
update

Isaac Abraham <notifications@github.com> schrieb am Do., 14. Nov. 2019,
17:23:

**Comment by isaacabraham** [comment]
Hoppla :-) So, I can confirm that the latest Paket doesn't do this any more :-)
