### ISSUE TITLE
does paket verify nuget packages signatures?

### ISSUE THREAD

**Issue by NahumLitvin** [fsprojects/Paket#3832]
I could not find documentation about this.
https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-verify
does paket verify signed nuget packages validity?

**Comment by JohnyWS** [comment]
This being a cross-platform wrapper, then no.

That feature is barely supported in nuget cli: "Verification of signed packages is not yet supported in .NET Core, under Mono, or on non-Windows platforms."

It would be interesting to have, if, and only if, it will be implemented in .NET 5 - but since it is not in .NET Core yet, I doubt it will make the cut for the NuGet team.

(NB: I'm not a maintainer, but I crawled the source code through for the use of the term "verify" to confirm it)

**Comment by joelverhagen** [comment]
As of NuGet 5.8 (.NET SDK version 5.0), package signature verification is supported cross-platform:
https://docs.microsoft.com/en-us/nuget/release-notes/nuget-5.8#summary-whats-new-in-58

I just wanted to give a head up since perhaps now it's more feasible to support package signature verification in Paket. For example, the NuGet signature verification is implemented in the [NuGet.Packaging](https://www.nuget.org/packages/NuGet.Packaging/5.8.1) package when targeting `net5.0`.

This is `dotnet nuget verify` on my Ubuntu 20.04 WSL.

```console
joel@jver-n-3:~$ dotnet nuget verify paket.6.0.0-beta8.nupkg -v normal

Verifying Paket.6.0.0-beta8
/home/joel/paket.6.0.0-beta8.nupkg
Signature Hash Algorithm: SHA256
Timestamp: 12/12/2020 22:38:19
Verifying repository primary signature's timestamp with timestamping service certificate:
  Subject Name: CN=Symantec SHA256 TimeStamping Signer - G3, OU=Symantec Trust Network, O=Symantec Corporation, C=US
  SHA1 hash: A9A4121063D71D48E8529A4681DE803E3E7954B0
  SHA256 hash: C474CE76007D02394E0DA5E4DE7C14C680F9E282013CFEF653EF5DB71FDF61F8
  Issued by: CN=Symantec SHA256 TimeStamping CA, OU=Symantec Trust Network, O=Symantec Corporation, C=US
  Valid from: 12/22/2017 16:00:00 to 03/22/2029 16:59:59
Signature type: Repository
nuget-v3-service-index-url: https://api.nuget.org/v3/index.json
nuget-package-owners: agross, fsprojects, matthid, mavnn, sforkmann
Verifying the repository primary signature with certificate:
  Subject Name: CN=NuGet.org Repository by Microsoft, O=NuGet.org Repository by Microsoft, L=Redmond, S=Washington, C=US
  SHA1 hash: 8FB6D7FCF7AD49EB774446EFE778B33365BB7BFB
  SHA256 hash: 0E5F38F57DC1BCC806D8494F4F90FBCEDD988B46760709CBEEC6F4219AA6157D
  Issued by: CN=DigiCert SHA2 Assured ID Code Signing CA, OU=www.digicert.com, O=DigiCert Inc, C=US
  Valid from: 04/09/2018 17:00:00 to 04/14/2021 05:00:00

Successfully verified package 'Paket.6.0.0-beta8'.
```
