### ISSUE TITLE
import_targets: false has no effect (on Gprc.Tools in netcoreapp3.1 F# exe)

### ISSUE THREAD

**Issue by marklam** [fsprojects/Paket#4005]
### Description

Gprc.Tools stops the build from its targets file if the project being built is not a .csproj, but `import_targets: false` does not prevent those targets being loaded when used in the paket.references or paket.dependencies files.

(Found this because a package I added had Gprc.Tools as a dependency)

### Repro steps

```
mkdir \temp\whatever
cd \temp\whatever
dotnet new console -f netcoreapp3.1 -lang F#
dotnet new tool-manifest
dotnet tool install paket
dotnet paket convert-from-nuget
dotnet paket add Grpc.Tools --project whatever
edit the paket.references to include 'Grpc.Tools import_targets: false'
or edit the paket.dependencies to include 'nuget Grpc.Tools import_targets: false'
dotnet restore
dotnet build
```
Git repo containing the same: https://github.com/marklam/paket-import-targets-false

### Expected behavior

Project builds

### Actual behavior

Error from Gprc.Tools' targets file
`C:\Users\Mark\.nuget\packages\grpc.tools\2.37.0\build\_protobuf\Google.Protobuf.Tools.targets(51,5): error : Google.Protobuf.Tools proto compilation is only supported by default in a C# project (extension .csproj) [C:\temp\whatever.fsproj]`

### Known workarounds

None

**Comment by mvkara** [comment]
I was having this issue when importing Grpc.AspNetCore into an F# project since it takes Grpc.Tools as a dependency. Although I'm not sure why, since the proto classes are generated in another project. Effectively it means you can't host Grpc in F# using Paket.

I found a workaround that allows the build to pass. See here: https://github.com/grpc/grpc/issues/20515#issuecomment-629415019. Since you aren't actually compiling any proto files anyway (for myself this is done in another C# project and referenced in) all this does is bypass the validation and allow the build to pass.

Ideally however target imports from transitive dependencies could also be disabled.

**Comment by baronfel** [comment]
I think this is going to be similar to #4039: PackageReference nodes have [different values for `ExcludeAssets`](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets) that can be set to control this behavior in msbuild, and paket isn't setting all of them just yet. Thankfully, #4040 shows this is a pretty simple process to add, so threading through the current `import_targets` behavior into including `ExcludeAssets=build;buildMultitargeting;buildTransitive` should be pretty simple to do.
