### ISSUE TITLE
v7.1.2 and greater fail to install clitools

### ISSUE THREAD

**Issue by mkb137** [fsprojects/Paket#4144]
### Description

Projects listed as `clitool` in paket.dependencies fail to download in v7.1.2 and greater due to a missing .nupkg file.

Presumably this change is at fault:
[NuGet Cache: avoid duplicate nupkg file - #4135](https://github.com/fsprojects/Paket/pull/4135)

### Repro steps

1. Define a paket.dependencies file like so (the project doesn't appear to matter):

```
source https://api.nuget.org/v3/index.json

clitool BenchmarkDotNet 0.13.1
```

2. Run `paket.exe install` on 7.1.2 or greater

### Expected behavior
The package should install successfully.

### Actual behavior
The following error message is produced:

```
Download of BenchmarkDotNet 0.13.1 done in 5 seconds. (1783 kbit/s, 1 MB)
Something went wrong while downloading BenchmarkDotNet 0.13.1
Message: Could not find file 'C:\Users\Mike\.nuget\packages\benchmarkdotnet\0.13.1\benchmarkdotnet.0.13.1.nupkg'.
```

### Known workarounds

Revert to paket v. 7.0.2

**Comment by forki** [comment]
Cc @cdrnet

Mike Bennett ***@***.***> schrieb am Do., 21. Apr. 2022,
23:23:

**Comment by cdrnet** [comment]
Weird, since #4135's only effect should be that the temporary nupkg in `C:\Users\Mike\.nuget\packages\benchmarkdotnet\benchmarkdotnet.0.13.1.nupkg` is deleted afterwards - the one in the version subfolder which the error is about in `C:\Users\Mike\.nuget\packages\benchmarkdotnet\0.13.1\benchmarkdotnet.0.13.1.nupkg` should have been put there by NuGet.Packaging.PackageExtractor.InstallFromSourceAsync. Maybe this behaves differently for tools packages?

**Comment by cdrnet** [comment]
Although BenchmarkDotNet is a normal library package, not a tool package. Did you mean to specify it as "clitool" rather than "nuget"?

**Comment by cdrnet** [comment]
I can repro: when combining clitool with storage:packages. With 7.0.2 we end up with two nupkg, with 7.1.2 we end up with none. I'll have a look.
