### ISSUE TITLE
Paket update repeatedly re-installs content files

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/Paket#471]
I'm using FSharp.Data.SqlClient, which has a couple of content files in the package. I delete them from the projects that use the package because I don't want them. Whenever I do a paket update or install (not --force or --hard), the files re-appear, even if that specific dependency hasn't been updated.

BTW this isn't a new issue - it's just that it's finally annoyed me so much that I decided to raise it as an issue ;-)

**Comment by tpluscode** [comment]
@agross oh I totally missed `content none`. 
@isaacabraham See issue #202, which proposes a more fine-grained control over content files.

That said I think that `content none` should be enough in most cases. Unfortunately paket will never be NuGet in terms of automatization. It's a good thing IMO, albeit sometimes it is necessary to manually finish an installation - as in packages which add some `.targets` files.

Regarding `content none` (and other optional config switches) I think it would nice if it was possible to turn them on mid-dependencies file so that it only applied to selected packages:

```
source https://nuget.org/api/v2
nuget UnionArgParser // will install UnionArgParser content files

content none
nuget jQuery // but won't install jQuery content files
```

**Comment by dnauck** [comment]
Same problem here. I need content in one project and the assembly only in another project.

If i turn of content it will delete also the content from project 1 every time ;)

**Comment by forki** [comment]
I'm currently looking into this and propose a third state: `content: once` - this would not overwrite files.
I even consider to make this the default since it's the way nuget works.

what do you think?

/cc @simoncropp

**Comment by dnauck** [comment]
Nice idea. +1

**Comment by forki** [comment]
mhm. it doesn't seem to solve the fody case completely.
![image](https://cloud.githubusercontent.com/assets/57396/10224818/23817040-6860-11e5-90f3-810891fe363f.png)

As far as I understand it we only want to copy fodyweavers.xml once. the rest should be latest and greatest, right?
