### ISSUE TITLE
Refactor "layers" into folders

### ISSUE THREAD

**Issue by forki** [fsprojects/Paket#488]
We already have a somehow implicit layer architecture in the core project. Low level functions are on the top of the project, commands in the middle and public api on the bottom. 

I think we should make this more explicit and introduce folders. 
What do people think? 
Is there a suggested folder structure? 

/cc @mexx @theimowski @isaac_abraham

**Comment by mexx** [comment]
Currently I would not introduce folders, the `Paket.Core` project with 43 `.fs` files is small enough for me to find the stuff I'm working with.
Further I would prefer to go more in the direction of *Hexagonal Architecture* rather than layers.
With it I would group stuff by purpose rather than by level of abstraction.
