### ISSUE TITLE
Allow to opt-out of old frameworks

### ISSUE THREAD

**Issue by forki** [fsprojects/Paket#574]
As reported by @mausch in #307 

    source https://nuget.org/api/v2

    nuget NHibernate 4.0.2.4000
    nuget Cassette 2.4.2

returns a conflict:

![image](https://cloud.githubusercontent.com/assets/57396/5987655/0b99a7aa-a938-11e4-959b-ab5bcbffa38f.png)

this is because [NHIbernate wants Iesi.Collections (≥ 4.0 && < 5.0)](https://www.nuget.org/packages/NHibernate/4.0.3.4000) and [Cassette wants Iesi.Collections (< 4.0) but only for .NET 3.5](https://www.nuget.org/packages/Cassette).

But it would be fine if we could tell paket that Cassette is only used in .NET 4.0 and higher.

This is somewhat similar to @haf's idea in #322 which was a bit too much at that time.
But now we have all the bits already under the hood and only need to expose this to the `paket.dependencies` file.

To make it similar to the `paket.lock` file where this is already used I propose this:

    source https://nuget.org/api/v2

    nuget NHibernate 4.0.2.4000
    nuget Cassette 2.4.2 >= net40

**Comment by agross** [comment]
Paket gets more and more tweaking options for the user, which I consider a good thing. I think we need a unified syntax to parse these, be it the recently added `CopyLocal` or this `FrameworkConstraint` (what's it called internally?).

Ruby/bundler uses hashes for optional switches and I think we should settle on something similar.
```
nuget Foobar 1.2.3 CopyLocal = true, Framework = >= net40, Content = none
```

I would prefer if we used `:` instead of `=` to separate keys from values because `Framework = >= net40` needs brains to parse.

```
nuget Foobar 1.2.3 CopyLocal: true, Framework: >= net40, Content: none
```

Another thought on casing: Paket started with `source`, `nuget` etc. downcased (haven't tested if other casing would even work), but with the `CopyLocal` options we move in the Pascal case direction. I'd prefer a syntax that would be consistent in that regard.

```
nuget Foobar 1.2.3 copy_local: true, framework: >= net40, content: none
```

You're probably right if you say that it looks like Ruby now. But from a readability point of view, I think it works better than Pascal case.

**Comment by forki** [comment]
ok let's use 

    nuget Foobar 1.2.3 copy_local: true, framework: >= net40, content: none

please update this also in https://github.com/fsprojects/Paket/issues/569

**Comment by forki** [comment]
Success! The latest alpha version alows to use the following:

    source https://nuget.org/api/v2

    nuget NHibernate 4.0.2.4000
    nuget Cassette 2.4.2 framework: >= net40

![image](https://cloud.githubusercontent.com/assets/57396/5988470/a9c0a5e0-a961-11e4-94e5-557fefdb5b70.png)
