### ISSUE TITLE
Emtpy Choose MSBuild condition when adding FSharp.Core package

### ISSUE THREAD

**Issue by kurtschelfthout** [fsprojects/Paket#579]
Seems like paket is putting empty Choose conditions in my project files when I add FSharp.Core package. See https://github.com/fsharp/FsCheck/commit/163062f7053741b690754f0aed37f7fe42819af3

Sorry I did find a number of seemingly related issues, but not this exact thing, apologies if this is being tracked elsewhere.

**Comment by forki** [comment]
I can confirm this is a bug. I just tried with latest release.

Then I tried with latest alpha:

![image](https://cloud.githubusercontent.com/assets/57396/6023123/3f04aa54-abc2-11e4-8dda-5ecbb8cbed8b.png)

so it seems this is already fixed and even the xunit runner gets installed.

**Comment by forki** [comment]
oups. Now I see the real issue.

It seems we broke the `install --hard` mode. Then when conditions are empty because you already have FSharp.Core referenced (from the original fsproj template). If you run `paket install --hard` then we would normally remove the original reference and put everything into the when nodes.
This behaviour is broken. I'll try to fix it, but as a workaround you can manually remove the FSharp.Core references from the fsproj files and rerun `paket install`

**Comment by forki** [comment]
`paket install --hard` works now in latest release. You only have to call it once. Afterwards you can use `paket install`.

![image](https://cloud.githubusercontent.com/assets/57396/6023522/894bc022-abc5-11e4-970a-d27a40d106fa.png)

**Comment by kurtschelfthout** [comment]
:+1: also for fixing the xunit thing. 

Just to confirm: this bug is fixed in latest, but to get xunit.runners to work I need alpha?

**Comment by forki** [comment]
yep. 

since I want to hear +1 on the props/targets feature first.

**Comment by kurtschelfthout** [comment]
Brilliant, works. Sorry, did not know references from another issue would re-open.

https://github.com/fsharp/FsCheck/commit/14c2e9d6e9d4405b8d8a334000feff71effe5fd3
