### ISSUE TITLE
Microsoft.Bcl.Build.targets should not be added

### ISSUE THREAD

**Issue by ctaggart** [fsprojects/Paket#594]
`Microsoft.Bcl.Build.targets is being added to a `net45` project and it should not be when I add a `Microsoft.AspNet.WebApi.Client` dependency.
https://github.com/ctaggart/Paket09x/blob/master/Paket09x.fsproj#L327
```
<Import Project="packages\Microsoft.Bcl.Build\build\Microsoft.Bcl.Build.targets" Condition="Exists('packages\Microsoft.Bcl.Build\build\Microsoft.Bcl.Build.targets')" Label="Paket" />
 ```
```
git clone https://github.com/ctaggart/Paket09x.git
cd paket09x
.\paket.exe update --force --hard
Paket version 0.27.9.0
```

https://www.nuget.org/packages/Microsoft.AspNet.WebApi.Client/

![image](https://cloud.githubusercontent.com/assets/80104/6140089/70f8aaf2-b148-11e4-8885-54d7df6968ca.png)

![image](https://cloud.githubusercontent.com/assets/80104/6140080/56ad077e-b148-11e4-97eb-50f0ed228774.png)

When I put `nuget Microsoft.AspNet.WebApi.Client framework: net45`, should `Microsoft.Net.Http (>= 2.2.22)` show up in the lock file? I was hoping not.

**Comment by forki** [comment]
I assume it's an issue in the resolver. I will have time to look at this in
Friday.

**Comment by forki** [comment]
The issue was the parsing of conditional depencies which use portable frameworks. I created a naive fix for that case. It seems to help here. Please give it a try.

![image](https://cloud.githubusercontent.com/assets/57396/6185709/f05ec7ba-b371-11e4-89e6-dcd83afe5081.png)

![image](https://cloud.githubusercontent.com/assets/57396/6185711/f6e0dc18-b371-11e4-99e1-74cf5be89dd7.png)
