### ISSUE TITLE
exploring unlisted NuGet Gallery versions

### ISSUE THREAD

**Issue by ctaggart** [fsprojects/Paket#606]
`FSharp.Core 4.0.0` was unlisted in the NuGet Gallery, but Paket still explores it. What does `exploring` mean?
```
PS C:\Tachyus\e> .\.paket\paket.exe update --force --hard
Paket version 0.27.16.0
found: C:\Tachyus\e\paket.dependencies
```
```
  - fetching versions for FSharp.Core
    - exploring FSharp.Core 4.0.0
    - exploring FSharp.Core 3.1.2.1
```
https://www.nuget.org/packages/FSharp.Core

**Comment by forki** [comment]
This is a place for future optimization. 

We have the issue that some strange packages have unlisted all their versions. So we have a workaround which checks unlisted versions but takes the listed ones if they exist. Otherwise we take the unlisted version in order to not break already working projects.
