### ISSUE TITLE
Can't resolve dependency, when dep needs updating

### ISSUE THREAD

**Issue by haf** [fsprojects/Paket#648]
```
  Can't resolve:
    - FSharp.Actor-logary >= 3.0.2
       - from Logary 3.0.2
 Please try to relax some conditions.
```

https://www.nuget.org/packages/FSharp.Actor-logary/

Has 3.0.2.

So why can't it resolve?

**Comment by forki** [comment]
what's the dependencies file?

**Comment by haf** [comment]
It works when I first do:

paket update FSharp.Actor-logary
paket update Logary

Otherwise, I get the error.

I belive a file could be:

```
nuget FSharp.Actor-logary
nuget Logary
```

install 3.0.0 of both.

Now try `paket update Logary`.

**Comment by forki** [comment]
I don't get the error, but doesn't update via `paket update nuget logary`

the issue is that you have `nuget FSharp.Actor-logary` in the dependencies file and that causes paketto fix FSharp.Actor-logary to 3.0.0 which is incompatible to logary 3.0.2 - seems OK.

If you remove FSharp.Actor-logary from the dependencies file (since it's a indirect dependency) everything should work.

**Comment by haf** [comment]
How does that work when I want to update everything?

Like `paket update`? I suppse it unlocks everything then?

At what point on the line of a decreasing number of packets to update, doesn't Paket update all dependencies anymore?

**Comment by forki** [comment]
* `paket update` updates everything.
* `paket update nuget package x` fixes everything but x and all dependencies of x that are not listed in the paket.dependencies file

there are no other rules and as always I'm ope for improvements.

**Comment by haf** [comment]
Ok, thank you.
