### ISSUE TITLE
What version range of direct dependencies should ``pack`` use?

### ISSUE THREAD

**Issue by mavnn** [fsprojects/Paket#662]
You can easily end up with versions of packages in your lock files that are newer than the minimum requirement you listed in your dependencies file.

If you have a dependency on ``MyPackage ~> 3.2`` and your lock file currently lists ``MyPackage 3.4`` what should the requirement of the resulting nupkg be? [3.2, 4.0) or [3.4, 4.0)?

Opinions welcome!

**Comment by agross** [comment]
For strong-named dependencies we need to pin the version to the one in the lockfile. It's a use case I currently have and one that is very painful to adjust by hand after every `paket update`.

For dependencies that are not strong-named, I think we should go with >= lockfile < max version allowed by depfile. E.g. `[3.4, 4.0)` in the sample above. IMHO, it's safe because you (hopefully) proved that your package works with `3.4`.
