### ISSUE TITLE
Updating the bootstrapper/paket.targets

### ISSUE THREAD

**Issue by dnauck** [fsprojects/Paket#790]
Currently we don't have updates or update notifications for the bootstrapper.

We could either:
1. check for the latest release when running the bootstrapper and display a notification when a new release is available
2. check for the latest release when running the bootstrapper and auto-update its executable
   1. by Shadow Copying Assemblies 
   2. move the locked bootstrapper.exe, download a new bootstrapper and cleanup on next run
3. let paket.exe handle the bootstrapper like a dependency and display it on `paket outdated` or update it on `paket update`, etc.

It should also update the `paket.targets` file when required.

Current disadvantages:
- bootstrapper is updated on every paket.exe release even if there was no changes

**Comment by matthid** [comment]
Seriously wondering why this wasn't suggested earlier.
I'm voting for option "3" which seems to be the easiest to implement.
IMHO we should not complicate the bootstrapper if we don't really need to. For example "1" could be integrated in the paket startup code instead or as suggested in 'paket outdated' (which I would prefer).

**Comment by Stift** [comment]
I have thought about it earlie and thought about `paket.bootstrapper.exe --self`
I came to that point when github had problems some time ago and we implemented an alternative nuget download. The only problem I had so far with that is that in the nuget package is no paket.bootstraper.

**Comment by Stift** [comment]
BTW you can copy it over the current bootstrapper.exe to self update

**Comment by forki** [comment]
so we need a Paket.Boostrapper package?

**Comment by dnauck** [comment]
@Stift what about the ```paket.targets``` file?

How do we know when to run the update command? every time? or is ```paket.exe outdated``` running this?

**Comment by Stift** [comment]
@forki in case we want a self update via nuget we could need one

**Comment by Stift** [comment]
@dnauck have not considered yet the paket.target file, but could be done easily. Do we consider the paket.target as unchangeable and overwrite it without asking? I'm just asking because users could change it and are not aware of a change. 
My proposal is currently supporting ´paket.bootstrapper.exe --self´. I chose that because when we had outages of github it was difficult to even get paket.exe. Should we just show with ´paket outdated´ that the bootstrapper is outdated and show a suggestion.

**Comment by forki** [comment]
https://www.nuget.org/packages/Paket.BootStrapper/

**Comment by Stift** [comment]
Thank you @forki for the package I have included this now.

**Comment by Stift** [comment]
This issue is still open, because the request of @dnauck for updating the paket.targets file is still unresolved.
I had some time to think about this and thought about that we should maybe let the bootstrapper stick with downloading the latest paket.exe as functionality.
The `paket.targets` is originally downloaded by the `paket.exe` when you do `paket.exe autorestore on`. IMO we should bring the functionality somewhere near here.
My suggestion would be sth like `paket autorestore update`, to either only update the file or turn the feature off and on. Any other ideas?

**Comment by dnauck** [comment]
Currently the bootstrapper also updates itself via ```--self``` on every paket release. Also there is no warning if its outdated, etc.

**Comment by Stift** [comment]
That would be easily doable. We just display an info when updating that just checks the latest version an displays it. 
There is only one problem, that for the github download we cannot detect whether there is a real change @sforki. So each paket release we see immediately an outdated message. 

Am 4. Juni 2015 08:35:46 MESZ, schrieb Daniel Nauck <notifications@github.com>:

**Comment by forki** [comment]
Closing old issue.
