### ISSUE TITLE
Invalid assembly redirects

### ISSUE THREAD

**Issue by dzendras** [fsprojects/Paket#813]
There's a bug in resolving the assembly redirects.
If a package contains a couple of DLLs for each framework, currently the one with the highest version is taken. Unfortunately it's not always a good choice. Example:

packages\Caliburn.Micro\lib\net45\System.Windows.Interactivity.dll //Version 4.5.0.0
packages\Caliburn.Micro\lib\sl5\System.Windows.Interactivity.dll //Version 5.0.5.0
packages\Caliburn.Micro\lib\wp8\System.Windows.Interactivity.dll .//Version 3.9.5.0

So no matter what your project target framework is, you'll always get a redirect to Silverlight version, which might lead to a runtime error.

I found the piece of code that might need changing. I wish I could create a pull request, but I'm a bit afraid that's too complicated for a start. Also I cannot find any tests to the piece of code I'd change...

**Comment by isaacabraham** [comment]
Yes, this is a problem with the binding redirects - there's a number of other issues raised all around this issue. As you put it, if there are multiple versions of an assembly for different frameworks under the same nuget package, there's a chance the wrong one will be selected.

Ideally the code should be changed so that it identifies which version is the appropriate one to use based on the current framework version - the tricky bits are: -

1. I'm not sure that this information currently flows through the existing logic.
2. If you change the framework version that you're compiling against (in VS), you'll have the same problem because although paket puts in framework-specific assembly references, there's no such thing as such for binding redirects.

There are some tests around binding redirects (https://github.com/fsprojects/Paket/blob/master/tests/Paket.Tests/BindingRedirect.fs) but I'm not sure if the code that will need modifying is that code or the module that calls it.

**Comment by dzendras** [comment]
Yeah I know there are tests for BindingRedirects.fs.
However there are no binding redirect tests for:
 https://github.com/fsprojects/Paket/blob/a3fbc02aa6439ef2269050a35bb960aa3f3303a1/src/Paket.Core/InstallProcess.fs

I think that the bug can be fixed my modifying  applyBindingRedirects root extractedPackages.
Unfortunately there are no tests for it and there has been a couple of changes there already. I'm a bit afraid of modifying the code...

I guess we have the necessary information there. At the beginning we have:
extractedPackages
    |> Seq.map(fun (package, model:InstallModel) -> model.GetLibReferencesLazy.Force())

And an extracted package has ResolvedPackage. So I guess we could use

package.Settings.FrameworkRestrictions

to get the framework version we're interested in...

**Comment by dzendras** [comment]
I think that having it working properly during conversion from NuGet would be very welcome.
If you were recommended Paket and you decide to give it a go, and after calling convert-from-nuget you get runtime errors, you might get discouraged and fallback to NuGet.

**Comment by Stift** [comment]
Yeah this issue is really hard to solve. In my projects I switched back to handle the binding redirects in a different way. The problem is that paket does not know which version you gonna use beforehand because it's adding all versions with the choose element...

What I have done:
1. I added <AutoGenerateBindingRedirects>True</AutoGenerateBindingRedirects> to all my projects to ensure that msbuild takes care of that. (works since .net 4.5.1 IMO)
The build process creates a <assembly>.config that should have all redirects.
2. Unfortunately web projects won't work with that. As the redirects are not changing that much and very much get covered by testing I do the following on the Nuget Package Manager Console: ´Get-Projects -All | Add-BindingRedirect´ 

As I have control over my dependency update process, this is part of my procedure. Along with testing this of course

**Comment by reijerh** [comment]
(Possibly the same problem as I posted here: https://github.com/fsprojects/Paket/issues/703)

**Comment by matthid** [comment]
> If you change the framework version that you're compiling against (in VS), you'll have the same problem because although paket puts in framework-specific assembly references, there's no such thing as such for binding redirects.

Just a suggestion/idea:
How about generating an `app.config` for each framework and then adding some magic to the msbuild files to make it work (in the worst case copying some files on build-time if we can't find a simpler way). This would match with the philosophy of Paket to create entries which can be used on whatever the selected framework is. 

Even without the msbuild magic this would already help users by making the update-process a simple copy-paste from the framework specific `app.config`

**Comment by isaacabraham** [comment]
@matthid whilst I like that idea, I'm a bit worried about paket generating a million different config files - I'm already told on a regular basis that paket generates too much in the way of binding redirects! :-)

The first part though - of generating redirects based on the framework rather than just the highest version in the package - could be done now and would probably stop 80% of the issues people are seeing.

**Comment by matthid** [comment]
>  I'm a bit worried about paket generating a million different config files

Yes that might happen, maybe we need some way to tell Paket which frameworks we care about (which is of course another configuration :-)). Paket could even respect such a config to simplify the project files (default is to support everything).

> The first part though - of generating redirects based on the framework rather than just the highest version in the package - could be done now and would probably stop 80% of the issues people are seeing.

This leads to the question which framework? And how do we detect it? We can try to detect it from the `fsproj` files but I don't think that will work in all cases, because the `TargetFramework` property could be set by the msbuild invocation, for example within FAKE. So the correct one would not even appear in the `**proj` files. What about projects which build for multiple frameworks?

**Comment by isaacabraham** [comment]
mmmm, yes, right. Don't know the answer to that. I'm wondering what does nuget currently do? If we treat that as a baseline perhaps that's a good place to start. Apparently it uses MSBuild - so does it automatically regen configs after every build?

**Comment by matthid** [comment]
IIRC Visual Studio / NuGet has this notion of a single `TargetFramework` per project file. Which one can select in Project -> Properties -> Application -> Targetframework. I would assume NuGet just uses that no matter what...

>Apparently it uses MSBuild - so does it automatically regen configs after every build?

@Stift mentioned something like that above? I have never seen / used it. And apparently it doesn't work for web projects.

**Comment by isaacabraham** [comment]
@dzendras: Create a fork, make the changes there - I'm happy to review it once you've done it.

**Comment by dzendras** [comment]
@isaacabraham I'm afraid I won't have time to do it in the next two weeks...
