### ISSUE TITLE
Is it possible to specify local copy for references?

### ISSUE THREAD

**Issue by 7sharp9** [fsprojects/Paket#817]
I used to the convert-from-nuget option and local copy was set to true for all my references.  In that project I sorcifucally need some references to be set to copy local = false.

**Comment by forki** [comment]
http://fsprojects.github.io/Paket/nuget-dependencies.html#copy_local-settings like this?

**Comment by 7sharp9** [comment]
Can you get paket to re-update the proj files after you have changed that?

**Comment by forki** [comment]
ha. good question ;-)

usually you would run "paket install" and it would try to detect your changes in the dependencies file and just perform the "diff" (while keeping everything else fixed). This would work if you change the version requirements in the dependencies file. I assume this is not implemented for changing the copy local settings (will try to implement this soon).

So what you can do is the following:
* Run "paket update"
* Make sure you selectively stage the paket.lock file, so that you only commit the changes that are related to copy_local (and no version changes).

**Comment by 7sharp9** [comment]
I played about and I got one of my projects to update but the other is stuck, Ill have to update it manually :-(
