### ISSUE TITLE
Paket update does not finish (in reasonable amount of time)

### ISSUE THREAD

**Issue by Ian2020** [fsprojects/Paket#935]
Hi,

I've got a solution where a paket update operation has not finished after 14 hours. Memory is fine, it's only using CPU. It makes the occasional lookup on our NuGet feed but that does not appear to be the bottleneck. It is working - it just seems to have too much work to do.

I have logged the output using the -v flag and then translated it to something shorter to try and understand what's happening. My translated log is below - it's only a partial log as the log file quickly gets too big as its so verbose. Package names have been changed.

Each time Paket makes a choice to try and satisfy a constraint I output it. When it says "Trying different resolution" because it hit a problem I count the occurences then output "Dead ends {0}" when it finally back tracks and makes another choice. I hope that makes sense.

From the output below it appears the search space is getting ever larger with each back track of a previously chosen package. Paket gets slower and slower between each choice leading to the huge runtime I believe.

At this stage I just want to know if this could just be a problem with our packages - have we got too many dependencies? Should tighten our constraints to help limit the search space? Or is there a problem with Paket?

From looking at the actual conflict its trying to resolve I know that the second package choice it makes right at the start "Acme.Sophia.Isabella.Ava 1.0.073.4490" is the one that needs to be downgraded in order to resolve the problem. But it appears from the search that this will be one of the last things Paket tries as it works its way back up the chain.

It's hard to provide a working example without having to include loads of our packages but potentially I could try and do this if it's valuable.

    Paket chose Acme.Sophia.Emma.Olivia 1.0.073.4467
    Paket chose Acme.Sophia.Isabella.Ava 1.0.073.4490
    Paket chose Acme.Lily.Zoe 1.0.075.4492
    Paket chose Acme.Chloe.Mia 1.0.075.4589
    Paket chose Acme.Madison 1.0.075.4493
    Paket chose Acme.Emily.Ella 0.0.075.4043
    Paket chose Acme.Madelyn 0.0.075.4492
    Paket chose Acme.Abigail 0.0.075.4525
    Paket chose Acme.Aubrey.Addison 0.0.075.4499
    Paket chose Acme.Avery.Addison 0.0.075.4499
    Paket chose Acme.Layla.Isabella 0.0.075.4495
    Paket chose Hailey.Amelia 5.0.8
    Paket chose Hannah 1.2.10
    Paket chose Charlotte.Kaitlyn 1.1
    Paket chose Harper 2.2.1
    Paket chose Acme.Kaylee.Sophie 2.0.075.4540
      Dead ends  1
    Paket chose Acme.Kaylee.Sophie 2.0.075.4536
      Dead ends  1
    Paket chose Acme.Kaylee.Sophie 2.0.075.4492
      Dead ends  1
    Paket chose Acme.Kaylee.Sophie 2.0.075.4453
      Dead ends  1
    Paket chose Acme.Layla.Isabella 0.0.075.4351
      Dead ends  4
    Paket chose Acme.Layla.Isabella 0.0.075.4343
      Dead ends  4
    Paket chose Acme.Layla.Isabella 0.0.075.0073
      Dead ends  4
    Paket chose Acme.Layla.Isabella 0.0.073.4361
      Dead ends  4
    Paket chose Acme.Avery.Addison 0.0.075.4495
      Dead ends  20
    Paket chose Acme.Avery.Addison 0.0.075.4494
      Dead ends  20
    Paket chose Acme.Avery.Addison 0.0.075.4488
      Dead ends  20
    Paket chose Acme.Avery.Addison 0.0.075.4353
      Dead ends  20
    Paket chose Acme.Avery.Addison 0.0.075.4351
      Dead ends  20
    Paket chose Acme.Avery.Addison 0.0.075.4350
      Dead ends  20
    Paket chose Acme.Avery.Addison 0.0.075.4341
      Dead ends  20
    Paket chose Acme.Avery.Addison 0.0.075.4027
      Dead ends  20
    Paket chose Acme.Avery.Addison 0.0.075.4010
      Dead ends  20
    Paket chose Acme.Avery.Addison 0.0.073.4408
      Dead ends  20
    Paket chose Acme.Aubrey.Addison 0.0.075.4495
      Dead ends  220
    Paket chose Acme.Aubrey.Addison 0.0.075.4494
      Dead ends  220
    Paket chose Acme.Aubrey.Addison 0.0.075.4488
      Dead ends  220
    Paket chose Acme.Aubrey.Addison 0.0.075.4353
      Dead ends  220
    Paket chose Acme.Aubrey.Addison 0.0.075.4351
      Dead ends  220
    Paket chose Acme.Aubrey.Addison 0.0.075.4350
      Dead ends  220
    Paket chose Acme.Aubrey.Addison 0.0.075.4341
      Dead ends  220
    Paket chose Acme.Aubrey.Addison 0.0.075.4027
      Dead ends  220
    Paket chose Acme.Aubrey.Addison 0.0.075.4010
      Dead ends  220
    Paket chose Acme.Aubrey.Addison 0.0.075.0077
      Dead ends  220
    Paket chose Acme.Aubrey.Addison 0.0.073.4408
      Dead ends  220
    Paket chose Acme.Abigail 0.0.075.3972
      Dead ends  2640
    Paket chose Acme.Abigail 0.0.075.2210
      Dead ends  2640
    Paket chose Acme.Abigail 0.0.075.0134
      Dead ends  2640
    Paket chose Acme.Abigail 0.0.074.1057
      Dead ends  2640
    Paket chose Acme.Abigail 0.0.073.4251
      Dead ends  2640
    Paket chose Acme.Abigail 0.0.070.1879
      Dead ends  2640
    Paket chose Acme.Madelyn 0.0.075.4350
      Dead ends  18480
    Paket chose Acme.Madelyn 0.0.075.3958
      Dead ends  18480
    Paket chose Acme.Madelyn 0.0.075.2406
      Dead ends  18480
    Paket chose Acme.Madelyn 0.0.075.0069
      Dead ends  18480
    Paket chose Acme.Madelyn 0.0.073.4361
      Dead ends  18480
    Paket chose Acme.Madelyn 0.0.033.7368
      Dead ends  18480
    Paket chose Acme.Emily.Ella 0.0.075.4027
      Dead ends  129360
    ...

**Comment by forki** [comment]
Usually this problem exist if you have lots of dependencies and no
resolution exists. Then paket basically tries all combinations and this
might take a while. If you can somehow give me access to your project I can
take a deeper look.

If you want to find the conflict try to pin more and more packages in
dependencies file to concrete versions. This narrows the search space.

Hi,

I've got a solution where a paket update operation has not finished after
14 hours. Memory is fine, it's only using CPU. It makes the occasional
lookup on our NuGet feed but that does not appear to be the bottleneck. It
is working - it just seems to have too much work to do.

I have logged the output using the -v flag and then translated it to
something shorter to try and understand what's happening. My translated log
is below - it's only a partial log as the log file quickly gets too big as
its so verbose. Package names have been changed.

Each time Paket makes a choice to try and satisfy a constraint I output it.
When it says "Trying different resolution" because it hit a problem I count
the occurences then output "Dead ends {0}" when it finally back tracks and
makes another choice. I hope that makes sense.

From the output below it appears the search space is getting ever larger
with each back track of a previously chosen package. Paket gets slower and
slower between each choice leading to the huge runtime I believe.

At this stage I just want to know if this could just be a problem with our
packages - have we got too many dependencies? Should tighten our
constraints to help limit the search space? Or is there a problem with
Paket?

From looking at the actual conflict its trying to resolve I know that the
second package choice it makes right at the start "Acme.Sophia.Isabella.Ava
1.0.073.4490" is the one that needs to be downgraded in order to resolve
the problem. But it appears from the search that this will be one of the
last things Paket tries as it works its way back up the chain.

It's hard to provide a working example without having to include loads of
our packages but potentially I could try and do this if it's valuable.

Paket chose Acme.Sophia.Emma.Olivia 1.0.073.4467
Paket chose Acme.Sophia.Isabella.Ava 1.0.073.4490
Paket chose Acme.Lily.Zoe 1.0.075.4492
Paket chose Acme.Chloe.Mia 1.0.075.4589
Paket chose Acme.Madison 1.0.075.4493
Paket chose Acme.Emily.Ella 0.0.075.4043
Paket chose Acme.Madelyn 0.0.075.4492
Paket chose Acme.Abigail 0.0.075.4525
Paket chose Acme.Aubrey.Addison 0.0.075.4499
Paket chose Acme.Avery.Addison 0.0.075.4499
Paket chose Acme.Layla.Isabella 0.0.075.4495
Paket chose Hailey.Amelia 5.0.8
Paket chose Hannah 1.2.10
Paket chose Charlotte.Kaitlyn 1.1
Paket chose Harper 2.2.1
Paket chose Acme.Kaylee.Sophie 2.0.075.4540
  Dead ends  1
Paket chose Acme.Kaylee.Sophie 2.0.075.4536
  Dead ends  1
Paket chose Acme.Kaylee.Sophie 2.0.075.4492
  Dead ends  1
Paket chose Acme.Kaylee.Sophie 2.0.075.4453
  Dead ends  1
Paket chose Acme.Layla.Isabella 0.0.075.4351
  Dead ends  4
Paket chose Acme.Layla.Isabella 0.0.075.4343
  Dead ends  4
Paket chose Acme.Layla.Isabella 0.0.075.0073
  Dead ends  4
Paket chose Acme.Layla.Isabella 0.0.073.4361
  Dead ends  4
Paket chose Acme.Avery.Addison 0.0.075.4495
  Dead ends  20
Paket chose Acme.Avery.Addison 0.0.075.4494
  Dead ends  20
Paket chose Acme.Avery.Addison 0.0.075.4488
  Dead ends  20
Paket chose Acme.Avery.Addison 0.0.075.4353
  Dead ends  20
Paket chose Acme.Avery.Addison 0.0.075.4351
  Dead ends  20
Paket chose Acme.Avery.Addison 0.0.075.4350
  Dead ends  20
Paket chose Acme.Avery.Addison 0.0.075.4341
  Dead ends  20
Paket chose Acme.Avery.Addison 0.0.075.4027
  Dead ends  20
Paket chose Acme.Avery.Addison 0.0.075.4010
  Dead ends  20
Paket chose Acme.Avery.Addison 0.0.073.4408
  Dead ends  20
Paket chose Acme.Aubrey.Addison 0.0.075.4495
  Dead ends  220
Paket chose Acme.Aubrey.Addison 0.0.075.4494
  Dead ends  220
Paket chose Acme.Aubrey.Addison 0.0.075.4488
  Dead ends  220
Paket chose Acme.Aubrey.Addison 0.0.075.4353
  Dead ends  220
Paket chose Acme.Aubrey.Addison 0.0.075.4351
  Dead ends  220
Paket chose Acme.Aubrey.Addison 0.0.075.4350
  Dead ends  220
Paket chose Acme.Aubrey.Addison 0.0.075.4341
  Dead ends  220
Paket chose Acme.Aubrey.Addison 0.0.075.4027
  Dead ends  220
Paket chose Acme.Aubrey.Addison 0.0.075.4010
  Dead ends  220
Paket chose Acme.Aubrey.Addison 0.0.075.0077
  Dead ends  220
Paket chose Acme.Aubrey.Addison 0.0.073.4408
  Dead ends  220
Paket chose Acme.Abigail 0.0.075.3972
  Dead ends  2640
Paket chose Acme.Abigail 0.0.075.2210
  Dead ends  2640
Paket chose Acme.Abigail 0.0.075.0134
  Dead ends  2640
Paket chose Acme.Abigail 0.0.074.1057
  Dead ends  2640
Paket chose Acme.Abigail 0.0.073.4251
  Dead ends  2640
Paket chose Acme.Abigail 0.0.070.1879
  Dead ends  2640
Paket chose Acme.Madelyn 0.0.075.4350
  Dead ends  18480
Paket chose Acme.Madelyn 0.0.075.3958
  Dead ends  18480
Paket chose Acme.Madelyn 0.0.075.2406
  Dead ends  18480
Paket chose Acme.Madelyn 0.0.075.0069
  Dead ends  18480
Paket chose Acme.Madelyn 0.0.073.4361
  Dead ends  18480
Paket chose Acme.Madelyn 0.0.033.7368
  Dead ends  18480
Paket chose Acme.Emily.Ella 0.0.075.4027
  Dead ends  129360
...

—
Reply to this email directly or view it on GitHub
<https://github.com/fsprojects/Paket/issues/935>.

**Comment by forki** [comment]
after rereading your issue: I assume you hit a case where the [package boost heuristic](http://fsprojects.github.io/Paket/resolver.html#Package-conflict-boost) doesn't work as intended.

**Comment by Ian2020** [comment]
I'll check the log tomorrow and see what packages are involved in the conflicts - could be they are a long way down the dependency chain from the one that causes the grief in the first place...maybe I can add logging for the boost factors somehow to see what's going on...

**Comment by Ian2020** [comment]
After looking at our conflict again I think we probably fall into the first scenario you mentioned - we cannot resolve this conflict no matter how long Paket is given without someone changing the dependencies manually. I was wrong to say that downgrading one of the packages will solve it - this was based on a cut down paket.dependencies file which is not the same situation as that which causes the long runtime.

Due to the number of packages involved I cannot do a full analysis to confirm it can never be resolved but am happy that when these long updates occur we just need to use verbose and sort out our dependencies manually. It seems reasonable that with a high number of dependencies Paket will take a long time and cannot give a definitive answer until all possibilties are exhausted.

Thanks for your help anyway!
